### ISSUE TITLE
cifar10_cnn.R example fails (ValueError: output of generator should be a tuple...)

### ISSUE THREAD

**Issue by Cervus1983** [rstudio/keras#101]
I suspect that using image data generator causes the problem, as it works without it (data_augmentation = FALSE). Package version: 2.0.5.

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\mikzhi\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\mikzhi\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mikzhi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\keras\python\keras\engine\training.py", line 615, in data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\mikzhi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\keras\python\keras\preprocessing\image.py", line 804, in __next__
    return self.next(*args, **kwargs)
  File "C:\Users\mikzhi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\keras\python\keras\preprocessing\image.py", line 892, in next
    x = self.image_data_generator.random_transform(x.astype(K.floatx()))
  File "C:\Users\mikzhi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\keras\python\keras\preprocessing\image.py", line 603, in random_transform
    raise ImportError('Scipy is required for image transformations.')
ImportError: Scipy is required for image transformations.



Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None

Detailed traceback: 
  File "C:\Users\mikzhi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\keras\python\keras\models.py", line 1092, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\mikzhi\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\keras\python\keras\engine\training.py", line 1857, in fit_generator
    'or `(x, y)`. Found: ' + str(generator_output))
```

**Comment by jjallaire** [comment]
It actually looks to me like the issue may be that SciPy isn't installed.

If you update to the latest version of the keras package from GitHub:

devtools::install_github("rstudio/keras")

Then, execute the install_keras function:

library(keras)
install_keras

Then SciPy will be installed alongside Keras. Note that this will require
Anaconda (as installing SciPy within vanilla python involves building it
from source, which is not for the faint of heart!)

**Comment by Cervus1983** [comment]
Worked like a charm. Thanks a lot!
