### ISSUE TITLE
keras and tensorflow installation error

### ISSUE THREAD

**Issue by FSantosCodes** [rstudio/keras#1311]
hi, I applied this:

install.packages("keras")
reticulate::install_miniconda()
keras::install_keras()

ok, it installed but later it do not works (even after trying to pip uninstall tensorflow):

library(tensorflow)
tf$constant("Hellow Tensorflow")

Error: Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\Fabian\AppData\Local\r-miniconda\envs\r-reticulate\python.exe

Python exception encountered:
 AssertionError: Duplicate registrations for type 'experimentalOptimizer'

You can install TensorFlow using the install_tensorflow() function.

my system info:
Sys.info()
          sysname           release           version          nodename           machine             
        "Windows"          "10 x64"     "build 19042" "LAPTOP-DS00VTSI"          "x86-64" 

thanks for your help.

**Comment by t-kalinowski** [comment]
Thanks for filing. 

Many installation issues are resolved by running the following in a **fresh R session** (you can restart R in Rstudio with Ctrl+Shift+F10) :
```R
# install the development version of packages, in case the
# issue is already fixed but not on CRAN yet.
install.packages("remotes")
remotes::install_github(sprintf("rstudio/%s", c("reticulate", "tensorflow", "keras")))
reticulate::miniconda_uninstall() # start with a blank slate
reticulate::install_miniconda()
keras::install_keras()
```

Test to see if installation was successful.
```R
tensorflow::as_tensor("Hello World")
```

If the above snippet succeeded and you saw something like `tf.Tensor(b'Hello World', shape=(), dtype=string)`, then :tada:, you've successfully installed Tensorflow.

If the above installation failed, please gather some diagnostic info:
```R
reticulate::py_config()
tensorflow::tf_config()
reticulate::import("tensorflow")
reticulate::py_last_error()
sessionInfo()
```

Please copy and paste the FULL OUTPUT of running all three snippets, and be sure to enclose the output lines with three backticks (```) for monospace formatting.

**Comment by FSantosCodes** [comment]
thanks, I was able to install tensorflow with this snippet but only for the cpu capabilities. Do you know how I should proceed for get the gpu tensoflow version? I am stuck with this. I installed CUDA toolkit 11.6 for a GeForce RTX 3050 Ti Laptop GPU but not sure if I am missing something. 

#last line I ran
tensorflow::as_tensor("Hello World")
#ok it was installed but...
`Loaded Tensorflow version 2.8.0
2022-02-27 21:09:30.339215: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2022-02-27 21:09:30.339556: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-02-27 21:09:30.340278: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
tf.Tensor(b'Hello World', shape=(), dtype=string)`

#to check it
reticulate::py_config()
`python:         C:/Users/Fabian/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/Fabian/AppData/Local/r-miniconda/envs/r-reticulate/python38.dll
pythonhome:     C:/Users/Fabian/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:19:05) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Fabian/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.22.2`
tensorflow::tf_config()
`TensorFlow v2.8.0 ()
Python v3.8 (C:/Users/Fabian/AppData/Local/r-miniconda/envs/r-reticulate/python.exe)`
reticulate::import("tensorflow")
`Module(tensorflow)`
reticulate::py_last_error()
`NULL`
sessionInfo()
`R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)`

`Matrix products: default`

`locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252`    

`attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base`     

`loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7            here_1.0.1            lattice_0.20-45       png_0.1-7             rprojroot_2.0.2      
 [6] zeallot_0.1.0         rappdirs_0.3.3        grid_4.1.2            R6_2.5.1              jsonlite_1.7.2       
[11] magrittr_2.0.2        tfruns_1.5.0          rlang_0.4.12          remotes_2.4.2         whisker_0.4          
[16] Matrix_1.3-4          reticulate_1.24       generics_0.1.1        keras_2.8.0.9000      tools_4.1.2          
[21] compiler_4.1.2        base64enc_0.1-3       tensorflow_2.8.0.9000`

**Comment by harin-git** [comment]
Hi @t-kalinowski I've been also having trouble installing tensorflow and followed your instructions but no luck.
Any suggestions?

reticulate::py_config()
> python:         /home/rstudio/.local/share/r-miniconda/envs/r-reticulate/bin/python
libpython:      /home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/libpython3.8.so
pythonhome:     /home/rstudio/.local/share/r-miniconda/envs/r-reticulate:/home/rstudio/.local/share/r-miniconda/envs/r-reticulate
version:        3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)  [GCC 10.3.0]
numpy:          /home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/numpy
numpy_version:  1.23.3

tensorflow::tf_config()
>Valid installation of TensorFlow not found.
Python environments searched for 'tensorflow' package:
 /home/rstudio/.local/share/r-miniconda/envs/r-reticulate/bin/python3.8
Python exception encountered:
 Traceback (most recent call last):
  File "/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
ModuleNotFoundError: No module named 'tensorflow'
You can install TensorFlow using the install_tensorflow() function.
 
reticulate::import("tensorflow")
> Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'tensorflow'

reticulate::py_last_error()
> Traceback (most recent call last):
  File "/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
ModuleNotFoundError: No module named 'tensorflow'

 sessionInfo()
>R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

>Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

>locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
 [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

>loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5            compiler_4.0.2        pillar_1.4.6          prettyunits_1.1.1    
 [5] base64enc_0.1-3       keras_2.9.0.9000      remotes_2.4.2         xts_0.12-0           
 [9] tools_4.0.2           zeallot_0.1.0         pkgbuild_1.1.0        jsonlite_1.7.0       
[13] lubridate_1.7.9       lifecycle_1.0.3       tibble_3.0.3          lattice_0.20-41      
[17] pkgconfig_2.0.3       png_0.1-7             rlang_1.0.6           Matrix_1.2-18        
[21] cli_3.4.1             rstudioapi_0.11       curl_4.3              withr_2.5.0          
[25] dplyr_1.0.1           rappdirs_0.3.3        generics_0.0.2        vctrs_0.3.2          
[29] fastDummies_1.6.3     rprojroot_2.0.3       grid_4.0.2            tidyselect_1.1.0     
[33] here_1.0.1            reticulate_1.26-9000  glue_1.4.1            R6_2.4.1             
[37] processx_3.4.3        purrr_0.3.4           callr_3.4.3           TTR_0.24.3           
[41] magrittr_2.0.3        whisker_0.4           ps_1.3.4              tfruns_1.5.1         
[45] ellipsis_0.3.1        tensorflow_2.9.0.9000 crayon_1.3.4          zoo_1.8-8

**Comment by t-kalinowski** [comment]
Can you try without miniconda?
```R
library(reticulate)
miniconda_uninstall()
install_python()
virtualenv_create("r-tensorflow", install_python())
tensorflow::install_tensorflow(envname = "r-tensorflow")
```
The above should work without issue.

If you want to troubleshoot miniconda, you can try to access it directly from terminal and it you should see a more fullsome error message + traceback. My best guess is it's likely a BLAS+numpy incompatibility, which is possible if your Linux image / R build is loading a BLAS version that the pre-built numpy binaries can't use.
```bash
. ~/.local/share/r-miniconda/bin/activate
conda activate ~/.local/share/r-miniconda/envs/r-reticulate
~/.local/share/r-miniconda/envs/r-reticulate/bin/python -c \
  'import tensorflow as tf; print(tf.constant("HI"))'
```

**Comment by sunmck** [comment]
Hey, same for me, I can't get tensorflow running in my R environment. Would be very happy about some help :)

> reticulate::py_config()
```
python:         C:/Users/avinn/AppData/Local/Programs/Python/Python311/python.exe
libpython:      C:/Users/avinn/AppData/Local/Programs/Python/Python311/python311.dll
pythonhome:     C:/Users/avinn/AppData/Local/Programs/Python/Python311
version:        3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON_FALLBACK
```

> tensorflow::tf_config()
```
Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\avinn\AppData\Local\Programs\Python\Python311\python.exe

Python exception encountered:
 Traceback (most recent call last):
  File "C:\Users\avinn\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avinn\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\avinn\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorflow'


You can install TensorFlow using the install_tensorflow() function.
```

> reticulate::import("tensorflow")
```
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'tensorflow'
Run `reticulate::py_last_error()` for details.
```

> reticulate::py_last_error()

```
── Python Exception Message ────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\avinn\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avinn\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\avinn\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tensorflow'

── R Traceback ─────────────────────────────────────────────────────────────────
    ▆
 1. └─reticulate::import("tensorflow")
 2.   └─reticulate:::py_module_import(module, convert = convert)
```

> sessionInfo()
```
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=English_Germany.utf8  LC_CTYPE=English_Germany.utf8   
[3] LC_MONETARY=English_Germany.utf8 LC_NUMERIC=C                    
[5] LC_TIME=English_Germany.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_2.13.0

loaded via a namespace (and not attached):
 [1] base64enc_0.1-3        Matrix_1.5-4.1         lattice_0.21-8        
 [4] reticulate_1.32.0.9002 magrittr_2.0.3         rappdirs_0.3.3        
 [7] png_0.1-8              cli_3.6.1              grid_4.3.1            
[10] tfruns_1.5.1           compiler_4.3.1         rprojroot_2.0.3       
[13] here_1.0.1             rstudioapi_0.15.0      tools_4.3.1           
[16] whisker_0.4.1          Rcpp_1.0.11            rlang_1.1.1           
[19] jsonlite_1.8.7 
```

**Comment by t-kalinowski** [comment]
I think you need to uncheck the "Automatically activate project-local Python environments" in the rstudio preferences. 

![image](https://github.com/rstudio/keras/assets/8462255/555bc613-0d57-468d-af39-206cb33dbe7b)
