### ISSUE TITLE
Layer's input passed as `self` argument during the training

### ISSUE THREAD

**Issue by krzjoa** [rstudio/keras#1349]
Hi, 

The first version of my time series related package [`{aion}`](github.com/krzjoa/aion) (formerly: `{keras.tft}`) is almost finished, but I stuck with a problem the cause of which I can't identify for the moment. When I'm trying to run model training, I get the error message suggesting that on the Python's side the first input is passed as a value of `self` argument, which is obviosuly not correct. It results in an error presented below.

``` r
# install.packages("m5")
# devtools::install_github("krzjoa/aion")

# Dataset
library(m5)

# Neural Networks
library(aion)
library(keras)

# Data wrangling
library(dplyr, warn.conflicts=FALSE)
library(data.table, warn.conflicts=FALSE)
library(recipes, warn.conflicts=FALSE)

# ==============================================================================
#                           DATA PREPARATION
# ==============================================================================

train <- tiny_m5[date < '2016-01-01']

m5_recipe <-
  recipe(value ~ ., data=train) %>%
  step_mutate(item_id_idx=item_id, store_id_idx=store_id) %>%
  step_integer(item_id_idx, store_id_idx,
               wday, month,
               event_name_1, event_type_1,
               event_name_2, event_type_2,
               zero_based=TRUE) %>%
  step_naomit(all_predictors()) %>%
  prep()

train <- bake(m5_recipe, train)

# ==============================================================================
#                               CONFIG
# ==============================================================================

TARGET      <- 'value'
STATIC_CAT  <- c('store_id_idx')
STATIC_NUM  <- 'item_id_idx'
DYNAMIC_CAT <- c('event_name_1', 'event_type_1')
CATEGORICAL <- c(DYNAMIC_CAT, STATIC_CAT)
NUMERIC     <- c('sell_price', 'sell_price', 'item_id_idx')
KEY         <- c('item_id', 'store_id')
INDEX       <- 'date'
LOOKBACK    <- 28
HORIZON     <- 14
STRIDE      <- LOOKBACK
BATCH_SIZE  <- 32


# ==============================================================================
#                         PREPARING ARRAYS (TENSORS)
# ==============================================================================

c(x, y) %<-%
  make_arrays(
    data        = train,
    key         = KEY,
    index       = INDEX,
    lookback    = LOOKBACK,
    horizon     = HORIZON,
    stride      = STRIDE,
    target      = TARGET,
    static      = c(STATIC_CAT, STATIC_NUM),
    categorical = CATEGORICAL,
    numeric     = NUMERIC,
    shuffle     = TRUE
  )


# ==============================================================================
#                           MODEL DEFINITION
# ==============================================================================

tft <-
  model_tft(
    lookback                = LOOKBACK,
    horizon                 = HORIZON,
    past_numeric_size       = length(NUMERIC) + 1,
    past_categorical_size   = length(DYNAMIC_CAT),
    future_numeric_size     = length(NUMERIC),
    future_categorical_size = length(DYNAMIC_CAT),
    vocab_static_size       = 10, # dict_size(train, STATIC_CAT),
    vocab_dynamic_size      = c(31, 5), #dict_size(train, DYNAMIC_CAT),
    hidden_dim              = 10,
    state_size              = 5,
    num_heads               = 10,
    dropout_rate            = NULL,
    output_size             = 1
  )
#> Loaded Tensorflow version 2.10.0

tft %>%
  compile(optimizer='adam', loss='mae')

# ==============================================================================
#                                 TRAINING
# ==============================================================================

# This one works
# tft(x)

tft %>%
  fit(
    x = x,
    y = y
  )
#> Error in py_call_impl(callable, dots$args, dots$keywords): RuntimeError: in user code:
#> <... omitted ...>arguments received by layer "scaled_dot_attention" "                 f"(type ScaledDotAttention):
#>               • self=tf.Tensor(shape=(None, 42, 0), dtype=float32)
#>               • query=tf.Tensor(shape=(None, 42, 0), dtype=float32)
#>               • key=tf.Tensor(shape=(None, 42, 0), dtype=float32)
#>               • value=None
#>               • mask=None
#>               • return_attention_scores=True
#>             See `reticulate::py_last_error()` for details.
#>         
#>         See `reticulate::py_last_error()` for details.
#>     
#>     
#>     Call arguments received by layer "temporal_fusion_decoder" "                 f"(type TemporalFusionDecoder):
#>       • self=tf.Tensor(shape=(None, 42, 5), dtype=float32)
#>       • inputs=tf.Tensor(shape=(None, 5), dtype=float32)
#>       • context=None
#>       • return_attention_scores=False
#>     See `reticulate::py_last_error()` for details.
#> 
#> See `reticulate::py_last_error()` for details
```

<sup>Created on 2022-09-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

What is especially interesting is the fact that simple forward call works without any problems and returns a valid output tensor.
I'll try to solve it on my own, but maybe you can point out the potential causes. I use `{reticulate}` 1.26 and `{keras}` dev version (2.9.0.9000).

**Comment by t-kalinowski** [comment]
{aion} looks very nice! :sunglasses: 

I cloned and was able to reproduce the same bug. Unfortunatly, this _actual_ error message was being swallowed by other handlers up the stack, which makes it very unuseful for debugging purposes. (This makes a great testcase for enhancing the error handling in reticulate).

One way to prevent the error from being swallowed is to enter into a debugger closer to where the error is being emitted. Dropping into a debugger in the `call` method of `layer_scaled_dot_attention` and stepping through it while it's called w/ tracing tensors by the `fit` method, I saw that `dropout_rate` was `NULL`. Updating the value in your reprex to `dropout_rate = 0.1` gets the script past training. Unfortunately, it brings up another error message, which looks more interesting maybe, but might also might be an artifact of my non-orthodox nvidia drivers setup.

```
Traceback (most recent call last):
  File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'temporal_fusion_transformer/vsn/grn/layer_normalization/FusedBatchNormV3' defined at (most recent call last):
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 993, in train_step
      y_pred = self(x, training=True)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 557, in __call__
      return super().__call__(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/R/x86_64-pc-linux-gnu-library/4.2/reticulate/python/rpytools/call.py", line 13, in python_function
      res = rpycall.call_r_function(f, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/R/x86_64-pc-linux-gnu-library/4.2/reticulate/python/rpytools/call.py", line 13, in python_function
      res = rpycall.call_r_function(f, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/R/x86_64-pc-linux-gnu-library/4.2/reticulate/python/rpytools/call.py", line 13, in python_function
      res = rpycall.call_r_function(f, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/layers/normalization/layer_normalization.py", line 333, in call
      outputs, _, _ = tf.compat.v1.nn.fused_batch_norm(
Node: 'temporal_fusion_transformer/vsn/grn/layer_normalization/FusedBatchNormV3'
cuDNN launch failure : input shape ([1,32,2,1])
	 [[{{node temporal_fusion_transformer/vsn/grn/layer_normalization/FusedBatchNormV3}}]] [Op:__inference_train_function_28000]
```

**Comment by t-kalinowski** [comment]
{aion} looks very nice! :sunglasses: 

I cloned and was able to reproduce the same bug. Unfortunately, the _actual_ error message was being swallowed by other handlers up the stack, which makes it very unuseful for debugging purposes. (This makes a great testcase for enhancing the error handling in reticulate).

One way to prevent the error from being swallowed is to enter into a debugger closer to where the error is being emitted. Dropping into a debugger in the `call` method of `layer_scaled_dot_attention` and stepping through it while it's called w/ tracing tensors by the `fit` method, I saw that `dropout_rate` was `NULL`. Updating the value in your reprex to `dropout_rate = 0.1` gets the script past training. Unfortunately, it brings up another error message, which looks more interesting maybe, but might also just be an artifact of my (non-orthodox) nvidia setup.

```
Traceback (most recent call last):
  File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'temporal_fusion_transformer/vsn/grn/layer_normalization/FusedBatchNormV3' defined at (most recent call last):
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 993, in train_step
      y_pred = self(x, training=True)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/training.py", line 557, in __call__
      return super().__call__(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/R/x86_64-pc-linux-gnu-library/4.2/reticulate/python/rpytools/call.py", line 13, in python_function
      res = rpycall.call_r_function(f, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/R/x86_64-pc-linux-gnu-library/4.2/reticulate/python/rpytools/call.py", line 13, in python_function
      res = rpycall.call_r_function(f, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/R/x86_64-pc-linux-gnu-library/4.2/reticulate/python/rpytools/call.py", line 13, in python_function
      res = rpycall.call_r_function(f, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/home/tomasz/.virtualenvs/r-reticulate/lib/python3.10/site-packages/keras/layers/normalization/layer_normalization.py", line 333, in call
      outputs, _, _ = tf.compat.v1.nn.fused_batch_norm(
Node: 'temporal_fusion_transformer/vsn/grn/layer_normalization/FusedBatchNormV3'
cuDNN launch failure : input shape ([1,32,2,1])
	 [[{{node temporal_fusion_transformer/vsn/grn/layer_normalization/FusedBatchNormV3}}]] [Op:__inference_train_function_28000]
```

**Comment by krzjoa** [comment]
Thanks for the quick answer! :sunglasses: . I've used `dropout_rate = 0.1` and now it works. I was confused by the working forward pass (`tft(x)`), but on second thoughts I have to say that it makes sense. That's probably because `layer_dropout` functions differently in training and inference mode.
