### ISSUE TITLE
Installation Issue on win10: (NameError: name 'base_events' is not defined)

### ISSUE THREAD

**Issue by qdread** [rstudio/keras#1375]
I apologize for yet another installation issue. I cannot find this exact error. I have followed all the recommended steps, trying to install Keras in my preexisting Anaconda3 as well as Miniconda. In all cases I ultimately get the same error which I have been unable to find in any previous issue. This is the crux of the error (more detailed output below):

```
Error: .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: py_module_import(module, convert = convert)
  error: NameError: name 'base_events' is not defined
```

Any help would be greatly appreciated! I am at the end of my rope here :-P

### Output of `reticulate::py_config()`

```
python:         C:/Users/qdread/Anaconda3/envs/r-tensorflow/python.exe
libpython:      C:/Users/qdread/Anaconda3/envs/r-tensorflow/python311.dll
pythonhome:     C:/Users/qdread/Anaconda3/envs/r-tensorflow
version:        3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:23:48) [MSC v.1936 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/qdread/Anaconda3/envs/r-tensorflow/Lib/site-packages/numpy
numpy_version:  1.24.3

NOTE: Python version was forced by use_python() function
```

### Output of `tensorflow::tf_config()`

```
Error: .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: py_module_import(module, convert = convert)
  error: NameError: name 'base_events' is not defined
Run `reticulate::py_last_error()` for details.
```

### Output of `reticulate::import('tensorflow')`

```
Error in py_module_import(module, convert = convert) : 
  NameError: name 'base_events' is not defined
Run `reticulate::py_last_error()` for details.
```

### Output of `reticulate::py_last_error()`

```
── Python Exception Message ──────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\ANACON~1\envs\R-TENS~1\Lib\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\ANACON~1\envs\R-TENS~1\Lib\site-packages\tensorflow\python\__init__.py", line 105, in <module>
    from tensorflow.python.platform import test
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\ANACON~1\envs\R-TENS~1\Lib\site-packages\tensorflow\python\platform\test.py", line 20, in <module>
    from tensorflow.python.framework import test_util as _test_util
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\ANACON~1\envs\R-TENS~1\Lib\site-packages\tensorflow\python\framework\test_util.py", line 33, in <module>
    from absl.testing import parameterized
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\ANACON~1\envs\R-TENS~1\Lib\site-packages\absl\testing\parameterized.py", line 221, in <module>
    from absl.testing import absltest
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\ANACON~1\envs\R-TENS~1\Lib\site-packages\absl\testing\absltest.py", line 43, in <module>
    from unittest import mock  # pylint: disable=unused-import Allow absltest.mock.
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\ANACON~1\envs\R-TENS~1\Lib\unittest\mock.py", line 26, in <module>
    import asyncio
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Users\qdread\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qdread\ANACON~1\envs\R-TENS~1\Lib\asyncio\__init__.py", line 25, in <module>
    __all__ = (base_events.__all__ +
               ^^^^^^^^^^^
NameError: name 'base_events' is not defined

── R Traceback ───────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─reticulate::import("tensorflow")
 2.   └─reticulate:::py_module_import(module, convert = convert)
```

# session info

```
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] utf8_1.2.3             R6_2.5.1               base64enc_0.1-3        Matrix_1.6-0          
 [5] lattice_0.21-8         reticulate_1.32.0.9000 magrittr_2.0.3         rappdirs_0.3.3        
 [9] glue_1.6.2             generics_0.1.3         png_0.1-8              lifecycle_1.0.3       
[13] cli_3.6.1              fansi_1.0.4            vctrs_0.6.3            grid_4.3.1            
[17] zeallot_0.1.0          withr_2.5.0            tfruns_1.5.1           compiler_4.3.1        
[21] rstudioapi_0.15.0      tools_4.3.1            whisker_0.4.1          pillar_1.9.0          
[25] Rcpp_1.0.11            rlang_1.1.1            jsonlite_1.8.7        
```

**Comment by t-kalinowski** [comment]
Hi, no worries, thanks for reporting. 
Can you please paste the following into R console and then respond with a copy and paste of the full output from running the commands:

```r
install.packages("pak")
pak::pak("rstudio/tensorflow")
pak::pak("rstudio/keras")

reticulate::install_python()
keras::install_keras()
```

**Comment by t-kalinowski** [comment]
Thanks, I can reproduce. I will investigate.

**Comment by t-kalinowski** [comment]
This is now fixed in the development version of reticulate. Please install it with:

```r
pak::pak("rstudio/reticulate")
```

**Comment by qdread** [comment]
Thank you very much Tomasz! I appreciate your help. The installation proceeds as expected. Unfortunately I am now encountering an error at the model compile step which I may have to open a new issue about :-(

**Comment by t-kalinowski** [comment]
No worries, please open an issue whenever you find a bug.

**Comment by KeytoZ** [comment]
Thanks so munch. I had the same issue when I wanted to introduce reticulate in rstudio.I put the reticulate package into the rstudio directory and fixed the error of "base_event is not defiend".
