### ISSUE TITLE
Prediction Issue

### ISSUE THREAD

**Issue by SiSunAct** [rstudio/keras#1392]
My code:
 grad.beta<-predict(model.grad, keras_train_data_x, keras_train_data_y)
  grad.beta <- data.frame(grad.beta)

Hi, I am new user of Keras. When I try to predict the data with keras, it shows me this.
![捕获](https://github.com/rstudio/keras/assets/112710695/4491cdf0-a844-42ff-9f53-75592d88fdeb)

model is fine. model.grad has processed without any errors showing.
my tensorflow version is 2.1. numpy version is 1.16.4. python version is 3.6. keras version is 2.3.1.

**Comment by t-kalinowski** [comment]
- Can you please provide code I can run to reproduce the error locally? [{reprex}](https://reprex.tidyverse.org/) may be helpful.
- What is the output from running `reticulate::py_last_error()`? 
- Your tensorflow version and python versions are quite old, and no longer supported. You may want to upgrade (thought, I don't think that's the source of the error).

**Comment by Vingoal** [comment]
── Python Exception Message ──────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\eager\execute.py", line 61, in quick_execute
    num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: lambda_21/Identity:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 475, in _model_iteration
    total_epochs=1)
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 638, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\eager\function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\eager\function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\eager\function.py", line 545, in call
    ctx=ctx)
  File "C:\Users\huany\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow_core\python\eager\execute.py", line 75, in quick_execute
    "tensors, but found {}".format(keras_symbolic_tensors))
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'lambda_21/Identity:0' shape=(None,) dtype=float32>, <tf.Tensor 'Predictions_10/Identity:0' shape=(None, 3) dtype=float32>, <tf.Tensor 'lambda_21/strided_slice/stack:0' shape=(2,) dtype=int32>, <tf.Tensor 'lambda_21/strided_slice/stack_1:0' shape=(2,) dtype=int32>, <tf.Tensor 'lambda_21/strided_slice/stack_2:0' shape=(2,) dtype=int32>, <tf.Tensor 'Predictions_10/MatMul/ReadVariableOp:0' shape=(6, 3) dtype=float32>, <tf.Tensor 'dense_21/Identity:0' shape=(None, 6) dtype=float32>, <tf.Tensor 'dense_21/Tanh:0' shape=(None, 6) dtype=float32>, <tf.Tensor 'dense_21/MatMul/ReadVariableOp:0' shape=(12, 6) dtype=float32>, <tf.Tensor 'dense_22/Identity:0' shape=(None, 12) dtype=float32>, <tf.Tensor 'dense_22/Tanh:0' shape=(None, 12) dtype=float32>, <tf.Tensor 'dense_22/MatMul/ReadVariableOp:0' shape=(3, 12) dtype=float32>, <tf.Tensor 'input_11:0' shape=(None, 3) dtype=float32>]

── R Traceback ───────────────────────────────────────────────────────────────────────
    ▆
 1. ├─model.grad %>% predict(keras_train_data_x)
 2. ├─stats::predict(., keras_train_data_x)
 3. └─keras:::predict.keras.engine.training.Model(., keras_train_data_x)
 4.   ├─base::do.call(object$predict, args)
 5.   └─reticulate (local) `<python.builtin.method>`(...)
 6.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)

**Comment by t-kalinowski** [comment]
If you can condense the issue into a block of code that I can run to reproduce the error, I'm happy to take a look. (e.g., generating fake data with `runif()` or similar in the reprex).

**Comment by Vingoal** [comment]
This is from an article. Can you take a look of this picture. I can send you the data file and the code file later if you do not understand this picture.
![Uploading 2.PNG…]()

**Comment by Vingoal** [comment]
I just do not know the last part. How to run predict() with keras model?

**Comment by t-kalinowski** [comment]
- the link doesn't work for me (I get 404)
- Surely you can condense the issue into an MRE (and, odds are good that while condensing it down to a minimal reproducible example, you resolve the issue yourself :)

**Comment by Vingoal** [comment]
Thank you for the reply, t-kalinowski. I am currently busy to work on other articles. Please give me some time to condense the issue into an MRE. I think I still need your help in the future. Have a nice day.
