### ISSUE TITLE
Problems with tensorflow-gpu

### ISSUE THREAD

**Issue by pbhogale** [rstudio/keras#195]
Having followed every instruction on the keras.rstudio, tensorflow and Nvidia pages, I still cannot get keras+tensorflow+rstudio to work with my GPU.

here is what I did 
```{r}
devtools::install_github("rstudio/keras", force = TRUE)
library(keras)
use_condaenv("r-tensorflow", conda = "/home/u-name/anaconda2/bin/conda")
```
which gives..
```
Downloading GitHub repo rstudio/keras@master
from URL https://api.github.com/repos/rstudio/keras/zipball/master
Installing keras
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpMbJ0WS/devtoolsb7d4ee62d2/rstudio-keras-b942dd2'  \
  --library='/home/prasanna/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

* installing *source* package ‘keras’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (keras)
```
so far so good.
then, 
```{r}
install_keras(method = "conda", conda = "/home/u-name/anaconda2/bin/conda",  tensorflow = "gpu")
```
which gives..
```
Using r-tensorflow conda environment for TensorFlow installation
Determining latest release of TensorFlow...done
Installing TensorFlow...
Collecting tensorflow-gpu==1.4.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl
  Using cached https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp27-none-linux_x86_64.whl
Collecting enum34>=1.1.6 (from tensorflow-gpu==1.4.0)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting backports.weakref>=1.0rc1 (from tensorflow-gpu==1.4.0)
  Using cached backports.weakref-1.0.post1-py2.py3-none-any.whl
Collecting wheel (from tensorflow-gpu==1.4.0)
  Using cached wheel-0.30.0-py2.py3-none-any.whl
Collecting mock>=2.0.0 (from tensorflow-gpu==1.4.0)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting tensorflow-tensorboard<0.5.0,>=0.4.0rc1 (from tensorflow-gpu==1.4.0)
  Using cached tensorflow_tensorboard-0.4.0rc3-py2-none-any.whl
Collecting numpy>=1.12.1 (from tensorflow-gpu==1.4.0)
  Using cached numpy-1.13.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting protobuf>=3.3.0 (from tensorflow-gpu==1.4.0)
  Using cached protobuf-3.5.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six>=1.10.0 (from tensorflow-gpu==1.4.0)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow-gpu==1.4.0)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->tensorflow-gpu==1.4.0)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Collecting futures>=3.1.1; python_version < "3.2" (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Using cached futures-3.1.1-py2-none-any.whl
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow-gpu==1.4.0)
Collecting setuptools (from protobuf>=3.3.0->tensorflow-gpu==1.4.0)
  Using cached setuptools-37.0.0-py2.py3-none-any.whl
Installing collected packages: enum34, backports.weakref, wheel, funcsigs, six, pbr, mock, numpy, html5lib, bleach, futures, setuptools, protobuf, markdown, werkzeug, tensorflow-tensorboard, tensorflow-gpu
Successfully installed backports.weakref-1.0.post1 bleach-1.5.0 enum34-1.1.6 funcsigs-1.0.2 futures-3.1.1 html5lib-0.9999999 markdown-2.6.9 mock-2.0.0 numpy-1.13.3 pbr-3.1.1 protobuf-3.5.0 setuptools-37.0.0 six-1.11.0 tensorflow-gpu-1.4.0 tensorflow-tensorboard-0.4.0rc3 werkzeug-0.12.2 wheel-0.30.0
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/u-name/anaconda2/envs/r-tensorflow:
#
h5py                      2.7.0            py27h71d1790_1  
pillow                    4.2.1            py27h7cd2321_0  
pyyaml                    3.12             py27h2d70dd7_1  
requests                  2.18.4           py27hc5b0589_1  
scipy                     1.0.0            py27hf5f0f52_0  
Requirement already up-to-date: keras in /home/u-name/anaconda2/envs/r-tensorflow/lib/python2.7/site-packages
Requirement already up-to-date: pyyaml in /home/u-name/anaconda2/envs/r-tensorflow/lib/python2.7/site-packages (from keras)
Requirement already up-to-date: six>=1.9.0 in /home/u-name/anaconda2/envs/r-tensorflow/lib/python2.7/site-packages (from keras)
Requirement already up-to-date: scipy>=0.14 in /home/u-name/anaconda2/envs/r-tensorflow/lib/python2.7/site-packages (from keras)
Requirement already up-to-date: numpy>=1.9.1 in /home/u-name/anaconda2/envs/r-tensorflow/lib/python2.7/site-packages (from keras)

Installation complete.
```

no problems there either. 
then, 

```{r}
library(keras)
use_condaenv("r-tensorflow", conda = "/home/u-name/anaconda2/bin/conda")
mnist <- dataset_mnist()
```
gives
```
Error: ImportError: Traceback (most recent call last): File "/home/u-name/anaconda2/envs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module> from tensorflow.python.pywrap_tensorflow_internal import * File "/home/u-name/anaconda2/envs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module> _pywrap_tensorflow_internal = swig_import_helper() File "/home/u-name/anaconda2/envs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory Failed to load the native TensorFlow runtime. See https://www.tensorflow.org/install/install_sources#common_installation_problems for some common reasons and solutions. Include the entire stack tr
6.
stop(e$message, call. = FALSE)
5.
on_error(result)
4.
py_resolve_module_proxy(x)
3.
`$.python.builtin.module`(keras, datasets)
2.
keras$datasets
1.
dataset_mnist()
```

In particular, `ImportError: libcublas.so.8.0: cannot open shared object file:` I cannot understand. I have this file, in the directory `usr/local/cuda-8.0` to which my environment variables point. I can only assume, the `r-tensorflow` environment somehow does not see this.

any work arounds ? help ?

**Comment by jjallaire** [comment]
These problems always boil down to the `LD_LIBRARY_PATH` of the current process. If you are running a desktop application like RStudio then you might not be getting the environment variables from the shell you think you are (see discussion here: https://tensorflow.rstudio.com/tools/installation_gpu.html#single-user-installation)
