### ISSUE TITLE
tensorflow = "1.4.0-gpu" failing 

### ISSUE THREAD

**Issue by jimr1603** [rstudio/keras#386]
System is Debian 9, so when I'm working with cuda 8. I've got this working with Python by forcing tensorflow 1.4.0. I ran install_keras(tensorflow="1.4.0-gpu"), but I get errors that suggest it's actually looking for cuda 9. 

> library(keras)     
> m <- dataset_mnist()
/home/james/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Error: ImportError: Traceback (most recent call last):
  File "/home/james/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/james/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/james/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this err
>

**Comment by jimr1603** [comment]
I have a **bad** solution. I went into ~/.virtualenv/r-tensorflow/ and deleted the tensorflow libraries, then went into the virtual env outside of R and manually installed the right version of tensorflow.

Clearly install_keras(tensorflow="1.4.0-gpu") isn't actually doing pip install tensorflow==1.4.0

**Comment by jimr1603** [comment]
I was confused between tensorflow and tensorflow-gpu. I've solved my problems, and they're not your problems.
