### ISSUE TITLE
Failure in getting keras() work with ImportError

### ISSUE THREAD

**Issue by amirfarrokh** [rstudio/keras#416]
I am trying to work with keras() in R using Windows (7 and 10 on two different PCs) and I get these errors. It has been days that I'm trying and zero progress. I installed Anaconda 3.6, then installed TensorFlow using:

`pip install tensorflow`

and then I installed keras using:

`pip install keras`

They were both successful. Then I do the following in R:
`library(keras)`
`install_keras()`

and it gets done successfully, too. Then I run:

`dataset_mnist()`

and I get this error:

> 
> Using TensorFlow backend.
> Error: ImportError: Traceback (most recent call last):
>   File "C:\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
>     return importlib.import_module(mname)
>   File "C:\ANACON~1\envs\R-TENS~1\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 571, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 922, in create_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> ImportError: DLL load failed with error code -1073741795
> 
> During handling of the above exception, another excepti

and when I run it again, I get this one:

> Using TensorFlow backend.
> Error: Python module keras was not found.
> 
> Detected Python configuration:
> 
> python:         C:\anaconda3\envs\r-tensorflow\python.exe
> libpython:      C:/anaconda3/envs/r-tensorflow/python36.dll
> pythonhome:     C:\ANACON~1\envs\R-TENS~1
> version:        3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
> Architecture:   64bit
> numpy:          C:\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
> numpy_version:  1.14.2
> keras:          C:\ANACON~1\envs\R-TENS~1\lib\site-packages\keras
> 
> python versions found: 
>  C:\anaconda3\envs\r-tensorflow\python.exe
>  C:\ANACON~1\python.exe
>  C:\anaconda3\python.exe

Your help is appreciated.

**Comment by amirfarrokh** [comment]
I finally figured it out. Instead of `pip install tensorflow` and `pip install keras`, I used `conda install --name r-tensorflow tensorflow` and `conda install --name r-tensorflow keras`, respectively. It was like a puzzle to solve, though. I would have mentioned in the book.
