### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed?

### ISSUE THREAD

**Issue by svcuonghvktqs** [rstudio/keras#417]
I'm trying to load mnist dataset:
```
> library(keras)
> mnist <- dataset_mnist()
```
but it shows me an error:
```
Error: ImportError: Traceback (most recent call last):
  File "C:\Users\svcuo\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\svcuo\ANACON~1\envs\R-TENS~1\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
```
Any idea about how to deal with this issue?

**Comment by pythonian1027** [comment]
getting the same error, already run through all other suggestions I could find,

**Comment by whatevergeek** [comment]
i'm getting the same error

**Comment by pythonian1027** [comment]
Got it to work by uninstalling Anaconda, and/or any other RStudio installer files. Reinstalling Anaconda and following this steps: https://www.r-bloggers.com/a-newbies-install-of-keras-tensorflow-on-windows-10-with-r/
Hope it helps, let me know if it works!
