### ISSUE TITLE
Resource exhausted: OOM when allocating tensor | Problem to compute on GPU

### ISSUE THREAD

**Issue by MediaInBrain** [rstudio/keras#461]
Dear all,

Following the work that I started [here](https://github.com/rstudio/keras/issues/444), I had little issues when trying to run my neural art transfer application on CPU but manage with the help of the community. 

Now I am trying to move on and implement the computation on my local GPU but unfortunately am encountering some problems (the only difference between the R script in [this post](https://github.com/rstudio/keras/issues/444) and the one here was to use install_keras(tensorflow = "gpu") to run the application on the GPU instead of the CPU from the R side).

Here is the two error I am getting:
- First when I load the model:
`2018-07-03 08:59:38.412648: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-03 08:59:38.479929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: Quadro K620 major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:03:00.0
totalMemory: 1.95GiB freeMemory: 1.61GiB
2018-07-03 08:59:38.479953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-03 08:59:38.897577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-03 08:59:38.897601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-03 08:59:38.897608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-03 08:59:38.897742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1370 MB memory) -> physical GPU (device: 0, name: Quadro K620, pci bus id: 0000:03:00.0, compute capability: 5.0)`

- Second (which must be linked to the first one) when I am trying to run the model:
`2018-07-03 16:01:06.492054: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.43MiB.  Current allocation summary follows.
2018-07-03 16:01:06.492115: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (256): 	Total Chunks: 23, Chunks in use: 23. 5.8KiB allocated for chunks. 5.8KiB in use in bin. 848B client-requested in use in bin.
2018-07-03 16:01:06.492132: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (512): 	Total Chunks: 3, Chunks in use: 3. 1.5KiB allocated for chunks. 1.5KiB in use in bin. 1.5KiB client-requested in use in bin.
2018-07-03 16:01:06.492144: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (1024): 	Total Chunks: 5, Chunks in use: 5. 5.2KiB allocated for chunks. 5.2KiB in use in bin. 5.0KiB client-requested in use in bin.
2018-07-03 16:01:06.492159: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (2048): 	Total Chunks: 7, Chunks in use: 7. 14.0KiB allocated for chunks. 14.0KiB in use in bin. 14.0KiB client-requested in use in bin.
2018-07-03 16:01:06.492171: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (4096): 	Total Chunks: 2, Chunks in use: 1. 12.5KiB allocated for chunks. 6.8KiB in use in bin. 6.8KiB client-requested in use in bin.
2018-07-03 16:01:06.492182: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (8192): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492193: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (16384): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492203: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (32768): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492213: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (65536): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492226: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (131072): 	Total Chunks: 3, Chunks in use: 1. 533.0KiB allocated for chunks. 144.0KiB in use in bin. 144.0KiB client-requested in use in bin.
2018-07-03 16:01:06.492239: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (262144): 	Total Chunks: 1, Chunks in use: 0. 288.0KiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492250: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (524288): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492260: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492272: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (2097152): 	Total Chunks: 3, Chunks in use: 3. 7.47MiB allocated for chunks. 7.47MiB in use in bin. 7.32MiB client-requested in use in bin.
2018-07-03 16:01:06.492282: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (4194304): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492292: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (8388608): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492302: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492313: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492328: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492338: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492351: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (268435456): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-07-03 16:01:06.492363: I tensorflow/core/common_runtime/bfc_allocator.cc:646] Bin for 2.43MiB was 2.00MiB, Chunk State: 
2018-07-03 16:01:06.492375: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13020c0000 of size 1280
2018-07-03 16:01:06.492389: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13020c0500 of size 2558464
2018-07-03 16:01:06.492396: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x1302330f00 of size 2558464
2018-07-03 16:01:06.492406: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a1900 of size 256
2018-07-03 16:01:06.492414: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a1a00 of size 256
2018-07-03 16:01:06.492420: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a1b00 of size 256
2018-07-03 16:01:06.492427: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a1c00 of size 256
2018-07-03 16:01:06.492434: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a1d00 of size 256
2018-07-03 16:01:06.492442: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a1e00 of size 512
2018-07-03 16:01:06.492449: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2000 of size 256
2018-07-03 16:01:06.492456: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2100 of size 256
2018-07-03 16:01:06.492462: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2200 of size 256
2018-07-03 16:01:06.492469: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2300 of size 256
2018-07-03 16:01:06.492476: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2400 of size 1024
2018-07-03 16:01:06.492483: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2800 of size 256
2018-07-03 16:01:06.492490: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2900 of size 256
2018-07-03 16:01:06.492497: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2a00 of size 256
2018-07-03 16:01:06.492504: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2b00 of size 256
2018-07-03 16:01:06.492511: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a2c00 of size 2048
2018-07-03 16:01:06.492518: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a3400 of size 256
2018-07-03 16:01:06.492525: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a3500 of size 256
2018-07-03 16:01:06.492534: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a3600 of size 256
2018-07-03 16:01:06.492541: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a3700 of size 256
2018-07-03 16:01:06.492548: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13025a3800 of size 2718720
2018-07-03 16:01:06.492555: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x1302840000 of size 256
2018-07-03 16:01:06.492562: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x1302840100 of size 256
2018-07-03 16:01:06.492569: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x1302840200 of size 256
2018-07-03 16:01:06.492575: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x1302840300 of size 256
2018-07-03 16:01:06.492582: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x1302840400 of size 256
2018-07-03 16:01:06.492589: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Free  at 0x1302840500 of size 5888
2018-07-03 16:01:06.492596: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x1302841c00 of size 256
2018-07-03 16:01:06.492603: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Free  at 0x1302841d00 of size 147456
2018-07-03 16:01:06.492610: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x1302865d00 of size 512
2018-07-03 16:01:06.492617: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Free  at 0x1302865f00 of size 294912
2018-07-03 16:01:06.492624: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028adf00 of size 512
2018-07-03 16:01:06.492631: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028ae100 of size 1024
2018-07-03 16:01:06.492638: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028ae500 of size 1024
2018-07-03 16:01:06.492645: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028ae900 of size 1024
2018-07-03 16:01:06.492652: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028aed00 of size 2048
2018-07-03 16:01:06.492658: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028af500 of size 2048
2018-07-03 16:01:06.492665: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028afd00 of size 2048
2018-07-03 16:01:06.492672: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028b0500 of size 2048
2018-07-03 16:01:06.492679: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028b0d00 of size 2048
2018-07-03 16:01:06.492685: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028b1500 of size 2048
2018-07-03 16:01:06.492692: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028b1d00 of size 6912
2018-07-03 16:01:06.492700: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Chunk at 0x13028b3800 of size 147456
2018-07-03 16:01:06.492707: I tensorflow/core/common_runtime/bfc_allocator.cc:665] Free  at 0x13028d7800 of size 250880
2018-07-03 16:01:06.492713: I tensorflow/core/common_runtime/bfc_allocator.cc:671]      Summary of in-use Chunks by size: 
2018-07-03 16:01:06.492723: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 23 Chunks of size 256 totalling 5.8KiB
2018-07-03 16:01:06.492732: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 3 Chunks of size 512 totalling 1.5KiB
2018-07-03 16:01:06.492740: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 4 Chunks of size 1024 totalling 4.0KiB
2018-07-03 16:01:06.492749: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 1280 totalling 1.2KiB
2018-07-03 16:01:06.492758: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 7 Chunks of size 2048 totalling 14.0KiB
2018-07-03 16:01:06.492766: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 6912 totalling 6.8KiB
2018-07-03 16:01:06.492774: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 147456 totalling 144.0KiB
2018-07-03 16:01:06.492783: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 2 Chunks of size 2558464 totalling 4.88MiB
2018-07-03 16:01:06.492791: I tensorflow/core/common_runtime/bfc_allocator.cc:674] 1 Chunks of size 2718720 totalling 2.59MiB
2018-07-03 16:01:06.492799: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Sum Total of in-use chunks: 7.65MiB
2018-07-03 16:01:06.492813: I tensorflow/core/common_runtime/bfc_allocator.cc:680] Stats: 
Limit:                     8716288
InUse:                     8017152
MaxInUse:                  8458496
NumAllocs:                      46
MaxAllocSize:              2718720

2018-07-03 16:01:06.492833: W tensorflow/core/common_runtime/bfc_allocator.cc:279] *****************************************************************************************x**___***__
2018-07-03 16:01:06.492882: W tensorflow/core/framework/op_kernel.cc:1295] OP_REQUIRES failed at constant_op.cc:75 : Resource exhausted: OOM when allocating tensor of shape [1,399,532,3] and type float
2018-07-03 16:01:06.495370: E tensorflow/core/common_runtime/executor.cc:660] Executor failed to create kernel. Resource exhausted: OOM when allocating tensor of shape [1,399,532,3] and type float
	 [[Node: gradients/Pow_grad/mul = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [1,399,532,3] values: [[[1 1 1]]]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
Exception tensorflow.python.framework.errors_impl.InvalidArgumentError: InvalidArgumentError() in <bound method _Callable.__del__ of <tensorflow.python.client.session._Callable object at 0x7fd0b238c110>> ignored `

` Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ResourceExhaustedError: OOM when allocating tensor of shape [1,399,532,3] and type float
	 [[Node: gradients/Pow_grad/mul = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [1,399,532,3] values: [[[1 1 1]]]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]] 
12.
stop(structure(list(message = "ResourceExhaustedError: OOM when allocating tensor of shape [1,399,532,3] and type float\n\t [[Node: gradients/Pow_grad/mul = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [1,399,532,3] values: [[[1 1 1]]]...>, _device=\"/job:localhost/replica:0/task:0/device:GPU:0\"]()]]", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = c("/home/gendarme/R/x86_64-pc-linux-gnu-library/3.4/reticulate/libs/reticulate.so(Rcpp::exception::exception(char const*, bool)+0x82) [0x7fd126bdc832]", 
    "/home/gendarme/R/x86_64-pc-linux-gnu-library/3.4/reticulate/libs/reticulate.so(Rcpp::stop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x27) [0x7fd126bdc967]",  ... 
11.
__exit__ at errors_impl.py#519
10.
__init__ at session.py#1441
9.
_make_callable_from_options at session.py#1480
8.
_make_callable at tensorflow_backend.py#2582
7.
_call at tensorflow_backend.py#2630
6.
__call__ at tensorflow_backend.py#2661
5.
f_outputs(list(image)) 
4.
eval_loss_and_grads(x) 
3.
fn(par, ...) 
2.
(function (par) 
fn(par, ...))(c(-60.4922265531495, -71.5439946164843, -95.6545739022549, 
57.9834863990545, -59.4124369504862, 66.0110761823598, 122.784543487243, 
55.6371527367737, -60.05912721809, 20.5817432869226, 121.091574612539,  ... 
1.
optim(array_reshape(x, dim = length(x)), fn = evaluator$loss, 
    gr = evaluator$grads, method = "L-BFGS-B", control = list(maxit = 15)) `

Here are all the specifics:
-Ubuntu version:
16.04

-Python version:
3.6.5

-Tensorflow version:
1.8.0

-Cuda version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

-CUDNN version:
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 5

-Specifics of GPU:
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K620         Off  | 00000000:03:00.0  On |                  N/A |
| 34%   38C    P8     1W /  30W |   1888MiB /  1999MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1133      G   /usr/lib/xorg/Xorg                           116MiB |
|    0      1961      G   compiz                                       122MiB |
|    0      4495      C   python                                        82MiB |
|    0     11078      C   /usr/lib/rstudio/bin/rsession               1560MiB |
+-----------------------------------------------------------------------------+

As I thought this might be more a python problem I tried to run a simple example to test tensorflow from Python which doesn't seem to run properly. Here is the code with the outcome.
`import tensorflow as tf
>>> hello = tf.constant('Hello, Tensorflow')
>>> sess = tf.Session()
2018-07-03 08:55:51.332631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-07-03 08:55:51.332705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-03 08:55:51.332727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-07-03 08:55:51.332746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-07-03 08:55:51.332945: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10 MB memory) -> physical GPU (device: 0, name: Quadro K620, pci bus id: 0000:03:00.0, compute capability: 5.0)
>>> print(sess.run(hello))
b'Hello, Tensorflow'`

I am new to GPU computing so I might be missing something obvious to have my application running.

If someone could help me to determine how to fix this it would be great!

Cheers,

Mathieu

**Comment by MediaInBrain** [comment]
Thanks Steve for directing me to this post.

After discussing with some people it seems simply that my GPU doesn't have enough memory. I will try to run the same script on a bigger machine and see if it fixes it. (moving back to cpu in my case made it work as well but takes forever (this was the main reason why I wanted to have it running on the GPU))

Cheers

**Comment by kevinykuo** [comment]
Have you tried different (smaller) batch sizes?

**Comment by MediaInBrain** [comment]
Yes I did try this and it did not work neither :(

I am now trying to run the same script but on a cluster equipped with Tesla K20m GPUs.

Here are the specifics:
-Cuda version 7.5
-Python version 2.7

When i am running my script I get this issue:
`Error: ImportError: Traceback (most recent call last):
  File "/home/gendarme/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/gendarme/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/gendarme/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
ab
Execution halted`

I suppose that this is due to the incompatibility of Keras expecting cuda 9.0 and the cuda 7.5 installed. Is there a way to fix this problem other than upgrading the cuda version?

Many thanks.

Cheers

**Comment by jjallaire** [comment]
You either need to upgrade to CUDA 9 or you need to install TensorFlow from source such that it works with CUDA 7.5 (there are no available TensorFlow binaries that work with CUDA 7.5, see https://stackoverflow.com/questions/42759360/how-to-switch-to-cuda7-5-after-install-tensorflow-using-whl-file)

**Comment by MediaInBrain** [comment]
Thank you very much jjallaire, it makes a lot of sense to install a version of tensorflow compatible with the cuda version already installed now that you said it. I will post on the outcome once tested.

Many thanks for the advice.

**Comment by MediaInBrain** [comment]
Little update on my problem.
I upgraded cuda to 8.0 then installed keras with tensorflow backend version 1.4.1. 
That still lead to an error which was lack of libcudnn.so.6. I installed cudnn 6.0 with conda and provided the path in my R script with Sys.setenv. 
After all of those changes my original script ran perfectly on the GPU.

Thank everybody for your help.

**Comment by vasanth4224** [comment]
Hi.. I have same error... anyone can tell me, how to change batch_size? I mean, I don't know, which file have batch size?

**Comment by celowsky** [comment]
@vasanth4224 you probably should find something likr pipeline.config to edit batch size.

**Comment by ahmedalmindelawy93** [comment]
i have the same error but i am using training for yolov3
can any one help me, i am so exhausted from trying everything
note : my nvedia is 1650 4gb
