### ISSUE TITLE
Rstudio Keras tensorflow gpu ImportError: libcublas when importing IMDB dataset

### ISSUE THREAD

**Issue by chuk-yong** [rstudio/keras#557]
Tensorflow version: 1.11.0
Cuda:9.0
R: 3.4.4
RStudio:1.1.456
-----------------------------------------------------------------------------------
When NOT in GPU mode, I can load the IMDB dataset no problem:
IMDB <- dataset_imdb(num_words = 10000)

When running with install_keras(tensorflow = "gpu"):
> imdb <- dataset_imdb(num_words = 10000)
Error: ImportError: Traceback (most recent call last):
  File "/home/chubuntu/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/chubuntu/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/chubuntu/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/chubuntu/anaconda3/envs/r-tensorflow/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/chubuntu/anaconda3/envs/r-tensorflow/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas
--------------------------------------------------------------------------------------
How to resolve this?

**Comment by skeydan** [comment]
I assume this occurs whenever you run something on GPU (not just IMDB)?

In that case you might want to check if it works with TF 1.10 which had binaries built against cuda 9.0.
TF 1.11 now builds against cuda 9.2:

https://github.com/tensorflow/tensorflow/releases/tag/v1.11.0

**Comment by chuk-yong** [comment]
I was following the instructions on [](https://www.tensorflow.org/install/pip)
and verified the installation with p`ython -c "import tensorflow as tf; print(tf.__version__)"
`

**Comment by skeydan** [comment]
Which installation instructions exactly? (How did you get the binary, assuming you installed the binary)?

Also, I don't think the above line really tests if gpu mode works.

I'd recommend looking for a simple Python example (e.g., from Keras or Tensorflow tutorials) that really "does something", to check if that correctly runs on gpu.
