### ISSUE TITLE
unable to use keras while seems correctly installed

### ISSUE THREAD

**Issue by JulietteLgls** [rstudio/keras#616]
Hi, I'm trying to install keras, it seems to work sucessfully : 
```
install.packages("keras")
library(keras)
use_condaenv("r-tensorflow")
install_keras()
```

Gives

```
>install.packages("keras")
essai de l'URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/keras_2.2.4.tgz'
Content type 'application/x-gzip' length 3803189 bytes (3.6 MB)
==================================================
downloaded 3.6 MB


The downloaded binary packages are in
	/var/folders/0k/w69qtt5d2fq_tswgy7xbkd080000gs/T//RtmpreeeRU/downloaded_packages
>library(keras)
>use_condaenv("r-tensorflow")
>install_keras()

Remove all packages in environment /anaconda3/envs/r-tensorflow:


## Package Plan ##

  environment location: /anaconda3/envs/r-tensorflow


The following packages will be REMOVED:

    asn1crypto:           0.24.0-py36_1003                     conda-forge
    blas:                 1.1-openblas                         conda-forge
    bzip2:                1.0.6-1                              conda-forge
    ca-certificates:      2018.11.29-ha4d7672_0                conda-forge
    certifi:              2018.11.29-py36_1000                 conda-forge
    cffi:                 1.11.5-py36h5e8e0c9_1                conda-forge
    chardet:              3.0.4-py36_1003                      conda-forge
    cryptography:         2.3.1-py36hdffb7b8_0                 conda-forge
    cryptography-vectors: 2.3.1-py36_1000                      conda-forge
    freetype:             2.9.1-h6debe1e_4                     conda-forge
    h5py:                 2.8.0-py36he5c79e1_5                 conda-forge
    hdf5:                 1.10.4-nompi_h5598ddc_1003           conda-forge
    idna:                 2.8-py36_1000                        conda-forge
    jpeg:                 9c-h470a237_1                        conda-forge
    libcxx:               4.0.1-hcfea43d_1                                
    libcxxabi:            4.0.1-hcfea43d_1                                
    libedit:              3.1.20170329-hb402a30_2                         
    libffi:               3.2.1-h475c297_4                                
    libgfortran:          3.0.0-1                              conda-forge
    libpng:               1.6.36-ha92aebf_0                    conda-forge
    libtiff:              4.0.10-he6b73bb_0                    conda-forge
    ncurses:              6.1-h0a44026_1                                  
    numpy:                1.15.4-py36_blas_openblashb06ca3d_0  conda-forge [blas_openblas]
    olefile:              0.46-py_0                            conda-forge
    openblas:             0.3.3-ha44fe06_1                     conda-forge
    openssl:              1.0.2p-h470a237_1                    conda-forge
    pillow:               5.3.0-py36hc736899_0                 conda-forge
    pip:                  18.1-py36_0                                     
    pycparser:            2.19-py_0                            conda-forge
    pyopenssl:            18.0.0-py36_1000                     conda-forge
    pysocks:              1.6.8-py36_1002                      conda-forge
    python:               3.6.6-h5001a0f_0                     conda-forge
    pyyaml:               3.13-py36h470a237_1                  conda-forge
    readline:             7.0-h1de35cc_5                                  
    requests:             2.21.0-py36_1000                     conda-forge
    scipy:                1.1.0-py36_blas_openblashb06ca3d_202 conda-forge [blas_openblas]
    setuptools:           40.6.2-py36_0                                   
    six:                  1.12.0-py36_1000                     conda-forge
    sqlite:               3.25.3-ha441bb4_0                               
    tk:                   8.6.8-ha441bb4_0                                
    urllib3:              1.24.1-py36_1000                     conda-forge
    wheel:                0.32.3-py36_0                                   
    xz:                   5.2.4-h1de35cc_4                                
    yaml:                 0.1.7-h470a237_1                     conda-forge
    zlib:                 1.2.11-h1de35cc_3                               

Creating r-tensorflow conda environment for TensorFlow installation...
Solving environment: ...working... done

## Package Plan ##

  environment location: /anaconda3/envs/r-tensorflow

  added / updated specs: 
    - python=3.6


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.03.07-0           
    certifi:         2018.11.29-py36_0      
    libcxx:          4.0.1-hcfea43d_1       
    libcxxabi:       4.0.1-hcfea43d_1       
    libedit:         3.1.20170329-hb402a30_2
    libffi:          3.2.1-h475c297_4       
    ncurses:         6.1-h0a44026_1         
    openssl:         1.1.1a-h1de35cc_0      
    pip:             18.1-py36_0            
    python:          3.6.7-haf84260_0       
    readline:        7.0-h1de35cc_5         
    setuptools:      40.6.2-py36_0          
    sqlite:          3.25.3-ha441bb4_0      
    tk:              8.6.8-ha441bb4_0       
    wheel:           0.32.3-py36_0          
    xz:              5.2.4-h1de35cc_4       
    zlib:            1.2.11-h1de35cc_3      

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use:
# >source activate r-tensorflow
#
# To deactivate an active environment, use:
# >source deactivate
#

Installing TensorFlow...
Collecting tensorflow==1.10.0 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.10.0-py3-none-any.whl
  Using cached https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.10.0-py3-none-any.whl
Collecting six>=1.10.0 (from tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting astor>=0.6.0 (from tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/35/6b/11530768cac581a12952a2aad00e1526b89d242d0b9f59534ef6e6a1752f/astor-0.7.1-py2.py3-none-any.whl
Collecting wheel>=0.26 (from tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
Collecting tensorboard<1.11.0,>=1.10.0 (from tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/c6/17/ecd918a004f297955c30b4fffbea100b1606c225dbf0443264012773c3ff/tensorboard-1.10.0-py3-none-any.whl
Collecting grpcio>=1.8.6 (from tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/43/bf/20fc60520e518fe1d1cab864e5210656cd3584d1fbeeeab98075219c3d84/grpcio-1.17.0-cp36-cp36m-macosx_10_7_intel.whl
Collecting absl-py>=0.1.6 (from tensorflow==1.10.0)
Collecting protobuf>=3.6.0 (from tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/c7/27/133f225035b9539f2dcfebcdf9a69ff0152f56e0120160ec5c972ea7deb9/protobuf-3.6.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting gast>=0.2.0 (from tensorflow==1.10.0)
Collecting setuptools<=39.1.0 (from tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/8c/10/79282747f9169f21c053c562a0baa21815a8c7879be97abd930dbcf862e8/setuptools-39.1.0-py2.py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow==1.10.0)
Collecting numpy<=1.14.5,>=1.13.3 (from tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/f6/cd/b2c50b5190b66c711c23ef23c41d450297eb5a54d2033f8dcb3b8b13ac85/numpy-1.14.5-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting werkzeug>=0.11.10 (from tensorboard<1.11.0,>=1.10.0->tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting markdown>=2.6.8 (from tensorboard<1.11.0,>=1.10.0->tensorflow==1.10.0)
  Using cached https://files.pythonhosted.org/packages/7a/6b/5600647404ba15545ec37d2f7f58844d690baf2f81f3a60b862e48f29287/Markdown-3.0.1-py2.py3-none-any.whl
Installing collected packages: six, astor, wheel, werkzeug, setuptools, protobuf, markdown, numpy, tensorboard, grpcio, absl-py, gast, termcolor, tensorflow
Successfully installed absl-py-0.6.1 astor-0.7.1 gast-0.2.0 grpcio-1.17.0 markdown-3.0.1 numpy-1.14.5 protobuf-3.6.1 setuptools-40.6.2 six-1.12.0 tensorboard-1.10.0 tensorflow-1.10.0 termcolor-1.1.0 werkzeug-0.14.1 wheel-0.32.3
Solving environment: ...working... done

## Package Plan ##

  environment location: /anaconda3/envs/r-tensorflow

  added / updated specs: 
    - h5py
    - pillow
    - pyyaml
    - requests
    - scipy


The following NEW packages will be INSTALLED:

    asn1crypto:           0.24.0-py36_1003                     conda-forge
    blas:                 1.1-openblas                         conda-forge
    bzip2:                1.0.6-1                              conda-forge
    cffi:                 1.11.5-py36h5e8e0c9_1                conda-forge
    chardet:              3.0.4-py36_1003                      conda-forge
    cryptography:         2.3.1-py36hdffb7b8_0                 conda-forge
    cryptography-vectors: 2.3.1-py36_1000                      conda-forge
    freetype:             2.9.1-h6debe1e_4                     conda-forge
    h5py:                 2.8.0-py36he5c79e1_5                 conda-forge
    hdf5:                 1.10.4-nompi_h5598ddc_1003           conda-forge
    idna:                 2.8-py36_1000                        conda-forge
    jpeg:                 9c-h470a237_1                        conda-forge
    libgfortran:          3.0.0-1                              conda-forge
    libpng:               1.6.36-ha92aebf_0                    conda-forge
    libtiff:              4.0.10-he6b73bb_0                    conda-forge
    numpy:                1.15.4-py36_blas_openblashb06ca3d_0  conda-forge [blas_openblas]
    olefile:              0.46-py_0                            conda-forge
    openblas:             0.3.3-ha44fe06_1                     conda-forge
    pillow:               5.3.0-py36hc736899_0                 conda-forge
    pycparser:            2.19-py_0                            conda-forge
    pyopenssl:            18.0.0-py36_1000                     conda-forge
    pysocks:              1.6.8-py36_1002                      conda-forge
    pyyaml:               3.13-py36h470a237_1                  conda-forge
    requests:             2.21.0-py36_1000                     conda-forge
    scipy:                1.1.0-py36_blas_openblashb06ca3d_202 conda-forge [blas_openblas]
    six:                  1.12.0-py36_1000                     conda-forge
    urllib3:              1.24.1-py36_1000                     conda-forge
    yaml:                 0.1.7-h470a237_1                     conda-forge

The following packages will be UPDATED:

    ca-certificates:      2018.03.07-0                                     --> 2018.11.29-ha4d7672_0 conda-forge
    certifi:              2018.11.29-py36_0                                --> 2018.11.29-py36_1000  conda-forge

The following packages will be DOWNGRADED:

    openssl:              1.1.1a-h1de35cc_0                                --> 1.0.2p-h470a237_1     conda-forge
    python:               3.6.7-haf84260_0                                 --> 3.6.6-h5001a0f_0      conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting keras
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting tensorflow-hub
  Using cached https://files.pythonhosted.org/packages/5a/76/18c9aaf24f1b888bafa40351493815050e100098b4782d634b307fb1ebc8/tensorflow_hub-0.2.0-py2.py3-none-any.whl
Collecting keras-preprocessing>=1.0.5 (from keras)
  Using cached https://files.pythonhosted.org/packages/fc/94/74e0fa783d3fc07e41715973435dd051ca89c550881b3454233c39c73e69/Keras_Preprocessing-1.0.5-py2.py3-none-any.whl
Collecting keras-applications>=1.0.6 (from keras)
  Using cached https://files.pythonhosted.org/packages/3f/c4/2ff40221029f7098d58f8d7fb99b97e8100f3293f9856f0fb5834bef100b/Keras_Applications-1.0.6-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pyyaml in /anaconda3/envs/r-tensorflow/lib/python3.6/site-packages (from keras) (3.13)
Requirement already satisfied, skipping upgrade: scipy>=0.14 in /anaconda3/envs/r-tensorflow/lib/python3.6/site-packages (from keras) (1.1.0)
Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in /anaconda3/envs/r-tensorflow/lib/python3.6/site-packages (from keras) (1.15.4)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /anaconda3/envs/r-tensorflow/lib/python3.6/site-packages (from keras) (1.12.0)
Requirement already satisfied, skipping upgrade: h5py in /anaconda3/envs/r-tensorflow/lib/python3.6/site-packages (from keras) (2.8.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.4.0 in /anaconda3/envs/r-tensorflow/lib/python3.6/site-packages (from tensorflow-hub) (3.6.1)
Requirement already satisfied, skipping upgrade: setuptools in /anaconda3/envs/r-tensorflow/lib/python3.6/site-packages (from protobuf>=3.4.0->tensorflow-hub) (40.6.2)
Installing collected packages: keras-preprocessing, keras-applications, keras, tensorflow-hub
Successfully installed keras-2.2.4 keras-applications-1.0.6 keras-preprocessing-1.0.5 tensorflow-hub-0.2.0

Installation complete.


Restarting R session...
```

So that's OK but then when I run
```
library(keras)
mnist <- dataset_mnist()
```

I get 

```
Erreur : ImportError: Traceback (most recent call last):
  File "/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/anaconda3/envs/r-tensorflow/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/anaconda3/envs/r-tensorflow/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/py
```

I've been looking in many other similar issues on line, here and on otherwebsites but nothing of what I found worked for me.
I'm under OSX 10.11.6 with R version 3.5.0 (2018-04-23), Anaconda 1.9 and Python 3.6.
If anyone could help I would really appreciate! Thanks :)

**Comment by JulietteLgls** [comment]
Hi 
Thanks for your answer. I thought about this explaination but hoped it was something else because the truth is my computer is too old to handle later versions of macOS....

Any chance i can found a version of tensorflow supported for my old guy?

**Comment by skeydan** [comment]
From this

https://stackoverflow.com/questions/51848122/installing-tensorflow-1-10-on-el-capitan-10-11-6

it seems like TF 1.9 could work.

**Comment by JulietteLgls** [comment]
I finally solve the problem using keras 2.0.8 and tensorflow 1.4.1

Thanks a lot for your help
