### ISSUE TITLE
Unable to install Keras in R

### ISSUE THREAD

**Issue by AkshayAshok180** [rstudio/keras#678]
I am trying to install keras in R studio but getting below error "Upload did not complete.Error: Error 1 occurred creating conda environment r-tensorflow". 
I installed latest Anaconda & installed both Keras & Tensorlow in Anaconda, and tried to run install_keras() but found below errors. Please someone help me with this issue

> install_keras()
Creating r-tensorflow conda environment for TensorFlow installation...
Solving environment: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\User\MINICO~1\lib\site-packages\requests\adapters.py", line 412, in send
        conn = self.get_connection(request.url, proxies)
      File "C:\Users\User\MINICO~1\lib\site-packages\requests\adapters.py", line 305, in get_connection
        proxy_url = parse_url(proxy)
      File "C:\Users\User\MINICO~1\lib\site-packages\urllib3\util\url.py", line 199, in parse_url
        raise LocationParseError(url)
    urllib3.exceptions.LocationParseError: Failed to parse: proxy.server.com:port
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\cli\main_create.py", line 11, in execute
        install(args, parser, 'create')
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\cli\install.py", line 235, in install
        force_reinstall=context.force,
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\subdir_data.py", line 95, in query
        self.load()
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\subdir_data.py", line 227, in _load
        mod_etag_headers.get('_mod'))
      File "C:\Users\User\MINICO~1\lib\site-packages\conda\core\subdir_data.py", line 437, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\User\MINICO~1\lib\site-packages\requests\sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\User\MINICO~1\lib\site-packages\requests\sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\User\MINICO~1\lib\site-packages\requests\sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\User\MINICO~1\lib\site-packages\requests\adapters.py", line 414, in send
        raise InvalidURL(e, request=request)
    requests.exceptions.InvalidURL: Failed to parse: proxy.server.com:port

`$ C:\Users\User\MINICO~1\Scripts\conda create --yes --name r-tensorflow python=3.6`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\User\MINICO~1
                 HOMEPATH=\Users\User
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
          MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
                     PATH=C:\Program Files\R\R-3.5.2\bin\x64;C:\WINDOWS\system32;C:\WINDOWS;C:\W
                          INDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Pr
                          ogram Files (x86)\ATI Technologies\ATI.ACE\Core-
                          Static;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL
                          Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft
                          SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL
                          Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\D
                          TS\Binn\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;;C:\Users\U
                          ser\AppData\Local\Programs\Microsoft VS Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL
                          Server\140\Tools\PowerShell\Modules\
       REQUESTS_CA_BUNDLE=<not set>
   RMARKDOWN_MATHJAX_PATH=C:/Program Files/RStudio/resources/mathjax-26
        RS_RPOSTBACK_PATH=C:/Program Files/RStudio/bin/rpostback
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\User\Documents\.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\Users\User\MINICO~1  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\User\MINICO~1\pkgs
                          C:\Users\User\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\User\MINICO~1\envs
                          C:\Users\User\AppData\Local\conda\conda\envs
                          C:\Users\User\Documents\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
Upload did not complete.Error: Error 1 occurred creating conda environment r-tensorflow

**Comment by skeydan** [comment]
>  installed both Keras & Tensorlow in Anaconda

What exactly do you mean by that? Do you mean you are running R & RStudio as  part of an Anaconda installation?
