### ISSUE TITLE
Unable to use keras from anaconda

### ISSUE THREAD

**Issue by rstub** [rstudio/keras#690]
I am working on a CentOS 7.5 machine where keras has been installed at the system level using anaconda. I can use it from python:

```
bash-4.2$ /opt/anaconda3/bin/python3
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
/opt/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
>>>
```

However, when trying to use it from R I get the following error:

``` r
library(keras)
use_python("/opt/anaconda3/bin/python3")
reticulate::py_config()
#> python:         /opt/anaconda3/bin/python3
#> libpython:      /opt/anaconda3/lib/libpython3.6m.so
#> pythonhome:     /opt/anaconda3:/opt/anaconda3
#> version:        3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)  [GCC 7.2.0]
#> numpy:          /opt/anaconda3/lib/python3.6/site-packages/numpy
#> numpy_version:  1.14.3
#> keras:          /opt/anaconda3/lib/python3.6/site-packages/keras
#> 
#> python versions found: 
#>  /opt/anaconda3/bin/python3
#>  /opt/anaconda3/bin/python
#>  /usr/bin/python
is_keras_available()
#> [1] FALSE
reticulate::import("keras")
#> Error in py_module_import(module, convert = convert): ImportError: Traceback (most recent call last):
#>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
#>     from tensorflow.python.pywrap_tensorflow_internal import *
#>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
#>     _pywrap_tensorflow_internal = swig_import_helper()
#>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
#>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
#>   File "/opt/anaconda3/lib/python3.6/imp.py", line 243, in load_module
#>     return load_dynamic(name, filename, file)
#>   File "/opt/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
#>     return _load(spec)
#> ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
#> 
#> 
#> Failed to load the native TensorFlow runtime.
#> 
#> See https://www.tensorflow.org/install/install_sources#common_installation_problems
#> 
#> for some common reasons and solutions.  Include the entire stack trace
#> above this error message when asking for help.
#> 
#> Detailed traceback: 
#>   File "/opt/anaconda3/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
#>     from . import utils
#>   File "/opt/anaconda3/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
#>     from . import conv_utils
#>   File "/opt/anaconda3/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
#>     from .. import backend as K
#>   File "/opt/anaconda3/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
#>     from .tensorflow_backend import *
#>   File "/opt/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
#>     import tensorflow as tf
#>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 28, in <module>
#>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
#>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
#>     from tensorflow.python import pywrap_tensorflow
#>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
#>     raise ImportError(msg)
```

<sup>Created on 2019-03-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Looking at the library in question with `ldd`  I get

```
bash-4.2$ ldd /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so | grep libstdc++
        libstdc++.so.6 => /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6 (0x00007f2b5d71b000)
```

i.e.   the anaconda internal C++ standard library is used, while above the system default version is used. I have tried setting `LD_LIBRARY_PATH` to include `/opt/anaconda3/lib` at the beginning, but without success.

Any advice how to procede? Is it possible to use keras from anaconda?

**Comment by skeydan** [comment]
Hi, I  am sorry but it is not officially supported. It might be possible to get it to work but we can't offer any advice here.

**Comment by rstub** [comment]
@skeydan What is not officially supported? The OS, anaconda, a system installation of keras, ...?

**Comment by skeydan** [comment]
Sorry this got mixed up with a different issue ("not supported" referring to using R/RStudio installed via Anaconda).

Are you using RStudio Server? How did you set `LD_LIBRARY_PATH`?

**Comment by rstub** [comment]
I am using RStudio Server (Pro). Since I have no shell access (besides the one offered by RStudio Server), I have tried to set `LD_LIBRARY_PATH` in a R:
```
Sys.setenv(LD_LIBRARY_PATH = paste("/opt/anaconda3/lib", Sys.getenv("LD_LIBRARY_PATH"), sep = ":"))
```


Alternatively I used a `.Renviron` file:

```
PATH=/opt/anaconda3/bin:${PATH}
LD_LIBRARY_PATH=/opt/anaconda3/lib:${LD_LIBRARY_PATH}
```


In both cases `Sys.getenv("LD_LIBRARY_PATH")` did show that `/opt/anaconda3/lib` was at the beginning of the library search path. However, the error remained unchanged.

**Comment by skeydan** [comment]
Please see this

https://community.rstudio.com/t/reticulate-issues-in-rstudio-server/16555/4

and this

https://support.rstudio.com/hc/en-us/articles/200552316-Configuring-the-Server

> External Libraries

> You can add elements to the default LD_LIBRARY_PATH for R sessions (as determined by the R ldpaths script) by adding an rsession-ld-library-path entry to the server config file. This might be useful for ensuring that packages can locate external library dependencies that aren't installed in the system standard library paths. For example:

```
rsession-ld-library-path=/opt/local/lib:/opt/local/someapp/lib
```

**Comment by rstub** [comment]
Thanks for that. We will give it a try.
