### ISSUE TITLE
Installing keras in 'rstudio' receive message "name 'compose' is not defined

### ISSUE THREAD

**Issue by sterlinggunn01** [rstudio/keras#697]
Trying to install keras in rstudio. When I run install_keras(), install generates this error message

"NameError: name 'compose' is not defined"

Not familiar enough with the package to understand what is going on. Any guidance would be appreciated.

Thanks

**Comment by skeydan** [comment]
Please try again after updating to the newest development versions from github:

```
devtools::install_github("rstudio/reticulate")
devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
```

and if you still have problems, report the complete output.

**Comment by sterlinggunn01** [comment]
Here's the output

devtools::install_github("rstudio/tensorflow")
Skipping install of 'tensorflow' from a github remote, the SHA1 (70e7fd1f) has not changed since last install.
  Use `force = TRUE` to force installation
> devtools::install_github("rstudio/keras")
Skipping install of 'keras' from a github remote, the SHA1 (ed8c28f2) has not changed since last install.
  Use `force = TRUE` to force installation
> install_keras()
Creating r-tensorflow conda environment for TensorFlow installation...
Traceback (most recent call last):
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 85, in _main
    from ..base.context import context
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/base/context.py", line 22, in <module>
    from ..common.configuration import (Configuration, LoadError, MapParameter, PrimitiveParameter,
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/common/configuration.py", line 41, in <module>
    from cytoolz.dicttoolz import merge
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/cytoolz/__init__.py", line 18, in <module>
    comp = compose
NameError: name 'compose' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/requests/packages/__init__.py", line 27, in <module>
    from . import urllib3
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'requests.packages.urllib3.packages.six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/MACKLORI/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 543, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 513, in get_info
    args.func(args, p)
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/conda/gateways/download.py", line 11, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
Error: Error 1 occurred creating conda environment r-tensorflow

**Comment by skeydan** [comment]
> File "/Users/MACKLORI/anaconda/lib/python3.6/site-packages/cytoolz/init.py", line 18, in
comp = compose
NameError: name 'compose' is not defined

To me this looks like a problem with Anaconda (the version of Anaconda you're using?)

**Comment by sterlinggunn01** [comment]
Thank you. I blew out all existing Python apps. The keras package has installed.

Many thanks for your help.
Sterling
