### ISSUE TITLE
Specific models trained in Keras R cannot be loaded in Python

### ISSUE THREAD

**Issue by lichen11** [rstudio/keras#702]
I followed the example here 
https://keras.rstudio.com/articles/examples/imdb_cnn_lstm.html
and saved a model as model %>% save_model_hdf5("my_model.h5"). I can successfully load this model in using load_model_hdf5. 

Then in Python, I tried to load the same model, with
    import keras
    from keras.models import load_model
    model = load_model("my_model.h5")

The error I received is 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/keras/models.py", line 270, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/lib64/python2.7/site-packages/keras/models.py", line 347, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/lib64/python2.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/lib64/python2.7/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/lib64/python2.7/site-packages/keras/models.py", line 1411, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "/usr/lib64/python2.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/lib64/python2.7/site-packages/keras/utils/generic_utils.py", line 146, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 1271, in from_config
    return cls(**config)
  File "/usr/lib64/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/keras/layers/convolutional.py", line 337, in __init__
    **kwargs)
TypeError: __init__() got multiple values for keyword argument 'data_format'

I am able to load CNN type of Keras models either in R or Python. I am wondering it's the LSTM layer that is causing the problem. The versions of Keras in R and Python are both 2.1.6.

**Comment by skeydan** [comment]
Hi, this is a pretty old version I unfortunately will not be able to help with.
However, if you install `reticulate`, `tensorflow` and `keras` fresh from github (using `devtools`) and then, install the current stable version of TensorFlow

```
install_tensorflow()
```

it should work - with one change to your Python code:
```
import tensorflow as tf
model = tf.keras.models.load_model("my_model.h5")
```
