### ISSUE TITLE
Tensorflow Import Error but works fine with Python

### ISSUE THREAD

**Issue by JamesHWade** [rstudio/keras#743]
Hello,

I am having issues get an import error, and I am confused on how to move forward. There seem to be similar issues in other threads, e.g., [#102](https://github.com/rstudio/keras/issues/102).

Note: the analogous code in Python on the same environment works fine running a Jupyter notebook.

```
> library(keras)
> use_condaenv("py35_tensorflow", required = TRUE)
> mnist <- dataset_mnist()
Error: ImportError: Traceback (most recent call last):
  File "/share/apps/anaconda-python/install/envs/py35_tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/share/apps/anaconda-python/install/envs/py35_tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/share/apps/anaconda-python/install/envs/py35_tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/share/apps/anaconda-python/install/envs/py35_tensorflow/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/share/apps/anaconda-python/install/envs/py35_tensorflow/lib/python3.5/imp.py", l
> reticulate::py_config()
python:         /share/apps/anaconda-python/install/envs/py35_tensorflow/bin/python
libpython:      /share/apps/anaconda-python/install/envs/py35_tensorflow/lib/libpython3.5m.so
pythonhome:     /share/apps/anaconda-python/install/envs/py35_tensorflow:/share/apps/anaconda-python/install/envs/py35_tensorflow
version:        3.5.2 |Anaconda 4.3.1 (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
numpy:          /share/apps/anaconda-python/install/envs/py35_tensorflow/lib/python3.5/site-packages/numpy
numpy_version:  1.15.0
keras:          /share/apps/anaconda-python/install/envs/py35_tensorflow/lib/python3.5/site-packages/keras

NOTE: Python version was forced by use_python function
> reticulate::py_module_available('keras') # must return TRUE
[1] FALSE
> reticulate::py_module_available('tensorflow') # must return TRUE
[1] FALSE
> reticulate::py_discover_config("keras") # more info on the python env, tf and keras
python:         /share/apps/anaconda-python/install/envs/py35_tensorflow/bin/python
libpython:      /share/apps/anaconda-python/install/envs/py35_tensorflow/lib/libpython3.5m.so
pythonhome:     /share/apps/anaconda-python/install/envs/py35_tensorflow:/share/apps/anaconda-python/install/envs/py35_tensorflow
version:        3.5.2 |Anaconda 4.3.1 (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
numpy:          /share/apps/anaconda-python/install/envs/py35_tensorflow/lib/python3.5/site-packages/numpy
numpy_version:  1.15.0
keras:          /share/apps/anaconda-python/install/envs/py35_tensorflow/lib/python3.5/site-packages/keras

NOTE: Python version was forced by use_python function
```

Any advice would be much appreciated!

**Comment by JamesHWade** [comment]
I found the issue, but it was specific to my machine.
