### ISSUE TITLE
Error: Installation of TensorFlow not found.

### ISSUE THREAD

**Issue by eafpres** [rstudio/keras#755]
On my local machine, my install of keras/tensorflow was broken by a devtools github install of another package.  Now I cannot get it to work any longer.

Windows 10
RStudio 1.1.383
R 3.5.1

from fresh session
remove.packages("keras")
remove.packages("tensorflow")

then
install.packages("keras")
library(keras)
install_keras(method = "conda", tensorflow = "gpu")
everything proceeds normally to completion

Then trying to use keras:
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\eafpres\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\eafpres\Anaconda3\pkgs\python-3.6.5-h0c2934d_0\python.exe
 C:\Users\eafpres\Anaconda3\python.exe
 C:\Users\eafpres\Anaconda3\python.exe

You can install TensorFlow using the install_tensorflow() function.

FYI:
> reticulate::py_config()
python:         C:\Users\eafpres\ANACON~1\python.exe
libpython:      C:/Users/eafpres/ANACON~1/python36.dll
pythonhome:     C:\Users\eafpres\ANACON~1
version:        3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\eafpres\ANACON~1\lib\site-packages\numpy
numpy_version:  1.14.3
tensorflow:     [NOT FOUND]

python versions found: 
 C:\Users\eafpres\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\eafpres\ANACON~1\pkgs\PYTHON~1.5-H\python.exe
 C:\Users\eafpres\ANACON~1\python.exe
 C:\Users\eafpres\Anaconda3\python.exe

**Comment by eafpres** [comment]
FYI:
> reticulate::conda_list()
          name                                                        python
1     ANACON~1                     C:\\Users\\eafpres\\Anaconda3\\python.exe
2 r-tensorflow C:\\Users\\eafpres\\Anaconda3\\envs\\r-tensorflow\\python.exe

**Comment by dfalbel** [comment]
This could be problems with the installation of the GPU drivers. 
Do you see an error when you try to import on tensorflow directly from python?

**Comment by eafpres** [comment]
When I first tried import tensorflow in Spyder, it gave an error that it could not find tensorflow.  So i ran 

pip install tensorflow-gpu
and tried again, getting a new error:
import tensorflow
Traceback (most recent call last):

  File "<ipython-input-1-d6579f534729>", line 1, in <module>
    import tensorflow

  File "C:\Users\eafpres\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\eafpres\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\eafpres\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\eafpres\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\eafpres\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\eafpres\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\eafpres\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\eafpres\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by eafpres** [comment]
So I did a complete conda install:
conda update -all
conda create -n keras-gpu python=3.6 numpy scipy keras-gpu
activate keras-gpu
I can then run a mnist training code from the command line and it correctly accesses the gpu and trains the model

I then added the Spyder version for keras-gpu in Anaconda navigator and now I can import keras there and it seems to be working Ok

Note that I did not touch the GPU drivers etc. (I have CUDA 9 installed) but the update -all may have installed CUDA 10.

I tried to reinstall keras etc. again in RStudio, but with the same results.  However, I notice it is referring to Python 3.6.5 whereas the installs above left me with Python 3.6.8.  I think somehow R is not looking in the right places, even though I'm doing the install within R Studio.

Any additional help would be welcome; I really need to get my R/Keras working again!

**Comment by dfalbel** [comment]
In this case, if you have a working conda env you can specify that you want to use this environment by running:

`reticulate::use_condaenv("keras-gpu")`

before loading keras.

**Comment by eafpres** [comment]
Thank you for that.

OK, that seems to load keras and tensorflow, but it doesn't work in practice so far.  In once case, this occurs--hard to exactly debug but appears to fail on the fit() call:

2019-04-23 09:07:50.249960: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-04-23 09:07:51.656578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 860M major: 5 minor: 0 memoryClockRate(GHz): 1.0195
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 1.64GiB
2019-04-23 09:07:51.657537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-23 09:08:04.940202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-23 09:08:04.940681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-04-23 09:08:04.940920: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-04-23 09:08:04.941309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1387 MB memory) -> physical GPU (device: 0, name: GeForce GTX 860M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Set session seed to 638182
2019-04-23 09:08:35.234855: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
2019-04-23 09:08:35.840701: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:35.841685: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:35.842425: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:35.961798: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:35.962296: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:35.962668: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:35.963076: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:35.963867: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:35.964302: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:36.173099: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-04-23 09:08:36.189201: W tensorflow/stream_executor/stream.cc:2130] attempting to perform BLAS operation using StreamExecutor without BLAS support

In another case, this occurs:

> data_gen <- flow_images_from_dataframe(image_names,
+                                          x_col = "file_paths",
+                                          y_col = "writer_id",
+                                          generator = image_gen,
+                                          target_size = c(64, 128),
+                                          color_mode = "greyscale",
+                                          class_mode = "sparse",
+                                          batch_size = 32)

Error in flow_images_from_dataframe(image_names, x_col = "file_paths",  : 
  Pandas (python module) must be installed in the same environment as Keras.Install it using reticulate::virtualenv_install("pandas", envname = "r-tensorflow") or reticulate::conda_install("pandas", envname = "r-tensorflow") depending on the kind of environment you are using.

I will try to follow the instructions for Pandas for this one; for the first one I have no idea what to do.

Also, is there any idea why this isn't working anyway in R without the conda env reference?
Is it possible I could try install_keras(method = "conda" ...) and would that make any difference?

**Comment by dfalbel** [comment]
The first error probably means that your GPU is out of memory. Try closing all sessions where TF might be loaded - including python sessions. You can also take a look at the GPU memory in the task manager to confirm this.

The second error is saying that pandas is missing in your environment. You can install it using:

```reticulate::conda_install("pandas", "keras-gpu")```

---

It should work by simply running `install_keras`, but it's too hard to debug on different environments. I would re-install/update conda and try again.

**Comment by eafpres** [comment]
@Daniel--Thanks!  
One the first one: Duh! (head slap).  I had Spyder open, plus a local Python session, both using keras with the gpu.  Closed all of that; my code runs now.

I will try the reticulate conda panda install and report.

**Comment by eafpres** [comment]
@dfalbel 
Thank you again.
I confirm it now works in both cases.
FYI, to use flow_images_from_dataframe() I had to also install pillow
reticulate::conda_install("pillow", envname = "keras-gpu")

**Comment by sepamostafa** [comment]
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\Dell\AppData\Local\r-miniconda\envs\r-reticulate\python.exe

You can install TensorFlow using the install_tensorflow() function.
