### ISSUE TITLE
Can't import keras into rstudio

### ISSUE THREAD

**Issue by LJPowerAct** [rstudio/keras#791]
I'm trying to get keras in RStudio for my Mac.

I can load the keras package and install it using install_keras() without any problems. 

When I try to import keras I get the following error:

```
Error in py_module_import(module, convert = convert) : 
  ImportError: Traceback (most recent call last):
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
Impor
```

I have zero python knowledge as I mainly use R. Could anyone help me interpret these errors and resolve the issue?

Any help appreciated.

Thanks

**Comment by dfalbel** [comment]
What do you mean by "importing keras". Do you see this error when you simply `library(keras)`?

**Comment by LJPowerAct** [comment]
It appears when I use import("keras") using the reticulate package. I get the same error if I try and use a keras package function e.g. if I type:

model <- keras_model_sequential() %>%
  layer_dense(units = 32, input_shape = c(784)) %>%
  layer_dense(units = 10, activation = "softmax")

library(keras) doesn't return any errors neither does install_keras()

**Comment by skeydan** [comment]
You shouldn't `import` keras, but `library` it.
So does this return an error:

```
library(keras)
model <- keras_model_sequential() %>%
layer_dense(units = 32, input_shape = c(784)) %>%
layer_dense(units = 10, activation = "softmax")
```

?

If so, what is your output of 
`reticulate::py_config()` and your `sessionInfo()`?

**Comment by LJPowerAct** [comment]
If write:

```
library(keras)
model <- keras_model_sequential() %>%
layer_dense(units = 32, input_shape = c(784)) %>%
layer_dense(units = 10, activation = "softmax")
```

the return is now:

Error: Python module tensorflow.python.keras was not found.

Detected Python configuration:

python:         /Users/LloydJones/anaconda2/envs/r-tensorflow/bin/python
libpython:      /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/libpython3.7m.dylib
pythonhome:     /Users/LloydJones/anaconda2/envs/r-tensorflow:/Users/LloydJones/anaconda2/envs/r-tensorflow
version:        3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/numpy
numpy_version:  1.16.3
tensorflow:     /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow

`py_config()` returns:

python:         /Users/LloydJones/anaconda2/envs/r-tensorflow/bin/python
libpython:      /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/libpython3.7m.dylib
pythonhome:     /Users/LloydJones/anaconda2/envs/r-tensorflow:/Users/LloydJones/anaconda2/envs/r-tensorflow
version:        3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/numpy
numpy_version:  1.16.3
tensorflow:     /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow

NOTE: Python version was forced by use_python function

`sessionInfo() `returns:

R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_1.13.1.9000 keras_2.2.4.1.9001     dplyr_0.8.1            reticulate_1.12       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       lattice_0.20-38  zeallot_0.1.0    crayon_1.3.4     assertthat_0.2.1
 [6] grid_3.6.0       R6_2.4.0         jsonlite_1.6     magrittr_1.5     pillar_1.4.0    
[11] tfruns_1.4       rlang_0.3.4      rstudioapi_0.10  whisker_0.3-2    Matrix_1.2-17   
[16] generics_0.0.2   tools_3.6.0      glue_1.3.1       purrr_0.3.2      compiler_3.6.0  
[21] base64enc_0.1-3  pkgconfig_2.0.2  tidyselect_0.2.5 tibble_2.1.1

**Comment by dfalbel** [comment]
Can you also send you `tensorflow::tf_config()` please?

**Comment by LJPowerAct** [comment]
That returns:

Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/LloydJones/anaconda2/envs/r-tensorflow/bin/python3.7

You can install TensorFlow using the install_tensorflow() function.
 
When I go to the directory there is no file for tensorflow but there is a folder called "site-packages" in that location that contains a folder called tensorflow.

I've tried running `install_tensorflow()` and retried `tf_config()` and got the error:
nstallation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/LloydJones/.virtualenvs/r-tensorflow/bin/python
 /Users/LloydJones/anaconda2/envs/r-tensorflow/bin/python3.7
 /usr/bin/python
 /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
 /Users/LloydJones/anaconda2/bin/python2.7

You can install TensorFlow using the install_tensorflow() function.

**Comment by dfalbel** [comment]
Can you try running `tensorflow::install_tensorflow(method = "conda")`?

**Comment by LJPowerAct** [comment]
Doing that gives warnings that a new version of conda exists but it goes on to complete the installation. When I run `tensorflow::install_tensorflow(method = "conda")` after doing the above I still get the same error:

Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/LloydJones/.virtualenvs/r-tensorflow/bin/python
 /Users/LloydJones/anaconda2/envs/r-tensorflow/bin/python3.7
 /usr/bin/python
 /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
 /Users/LloydJones/anaconda2/bin/python2.7

You can install TensorFlow using the install_tensorflow() function.

**Comment by dfalbel** [comment]
Now can you try running: `reticulate::virtualenv_remove("r-tensorflow")`?

**Comment by LJPowerAct** [comment]
Ok. That's done and the virtual environment is removed, still getting the same error that it's not installed. It's also still listing 
/Users/LloydJones/.virtualenvs/r-tensorflow/bin/python
as a location it's looking for it. Was `virtualenv_remove("r-tensorflow")` intended to make it stop looking in this path?

**Comment by dfalbel** [comment]
Yes, it should stop listing this location...
Maybe you can try running:

```
reticulate::use_python("/Users/LloydJones/anaconda2/envs/r-tensorflow/bin/python3.7", required = TRUE)
library(tensorflow)
tf_version()
```

**Comment by LJPowerAct** [comment]
That returns NULL

**Comment by dfalbel** [comment]
What happens you try importing tensorflow from python. If you type `/Users/LloydJones/anaconda2/envs/r-tensorflow/bin/python3.7` in your Terminal it should open a python console. What happens when you run `import tensorflow as tf`?

**Comment by LJPowerAct** [comment]
That returns the following error:

Traceback (most recent call last):
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _clock_gettime
  Referenced from: /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _clock_gettime
  Referenced from: /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/LloydJones/anaconda2/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.so


Failed to load the native TensorFlow runtime.

**Comment by dfalbel** [comment]
Ok, I see now. It seems that tensorflow is only supported on macOS 10.12.6 (Sierra) or later (64-bit) and you are running Running OS X El Capitan 10.11.6

I think the best solution is you update your OS. In the meantime I'll make installation function return a clear error message stating that you need macOS 10.12.6 or higher.

**Comment by LJPowerAct** [comment]
Thanks a lot for the help!

I thought I’d upgraded a few days ago but it looks like I tried to upgrade to Mojave which is incompatible with my Mac so it just decided to stay at El Capitan rather than going to the intermediate Sierra.

I’ve upgraded and everything is working fine now.
