### ISSUE TITLE
Custom wrapers failing on nightly

### ISSUE THREAD

**Issue by dfalbel** [rstudio/keras#801]
The following will segfault if using nightly version of TensorFlow:

```
library(keras)

# Custom wrapper class
CustomWrapper <- R6::R6Class(
  "CustomWrapper",
  
  inherit = KerasWrapper,
  
  public = list(
    weight_shape = NULL,
    weight_init = NULL,
    custom_weight = NULL,
    
    initialize = function(weight_shape,
                          weight_init) {
      self$weight_shape <- weight_shape
      self$weight_init <- weight_init
      
    },
    
    build = function(input_shape) {
      
      super$build(input_shape)
      
      self$custom_weight <- super$add_weight(
        name = "custom_weight",
        shape = self$weight_shape,
        initializer = self$weight_init,
        trainable = TRUE
      )
      
      regularizer <- k_sum(k_log(self$custom_weight))
      super$add_loss(regularizer)
      
    }
  )
)

# wrapper instantiator
wrapper_custom <-
  function(object,
           layer,
           weight_shape,
           weight_init,
           input_shape = NULL) {
    create_wrapper(
      CustomWrapper,
      object,
      list(
        layer = layer,
        weight_shape = weight_shape,
        weight_init = weight_init,
        input_shape = input_shape
      )
    )
  }


layer <- wrapper_custom(
  layer = layer_dense(units = 4),
  weight_shape = shape(1),
  weight_init = initializer_he_normal(),
  input_shape = shape(2)
)

obj <- layer$python_wrapper()
obj(layer_input(shape = 2))
```

This is the most minimal example I could get. It seems to be related to `tf.function` stuff, but I am not sure ...

Same problem with Custom layers and Custom models.

**Comment by skeydan** [comment]
Not sure this helps much, but it seems we're trying to convert a null pointer:

```
#0  0x00007f69a4fde7f3 in r_scalar_type (x=0x0) at python.cpp:536
#1  0x00007f69a4fe3ea8 in py_to_r (x=0x0, convert=<optimized out>) at python.cpp:614
#2  0x00007f69a4fe5cd7 in call_r_function (self=<optimized out>, args=<optimized out>, keywords=0x0) at python.cpp:1272
#3  0x00007f69a059b9d3 in PyCFunction_Call () from /home/key/anaconda3/envs/r-tensorflow/lib/libpython3.6m.so
```

This is from a core dump, perhaps we can make more progress if we find a way to live-debug this...

**Comment by skeydan** [comment]
actually just thinking we should probably test a python version before spending much more time, just to make sure it works there
