### ISSUE TITLE
Error when trying to install and run keras/tensorflow on computing cluster

### ISSUE THREAD

**Issue by warkentinmatt** [rstudio/keras#818]
Hi, 

So here is the context, I am trying to install `tensorflow` and `keras` from scratch on a computing cluster. The cluster OS is CentOS Linux 7. I do not have write access to where `R` is installed, so I have created an `R` directory in my home directory for installing packages. I have installed `tensorflow` and `keras` from GitHub using `devtools`. Both seemingly installed without issue.

After installing `keras`, I ran the following code:

```
> library(keras)
> install_keras(method = 'conda')
```

This created an `r-tensorflow` conda envrionment in ~/.conda/envs. Again, seemingly no issues in the installation.

To test drive `keras` I ran the following code (`$` is in bash shell; `>`  is in R interpreter):

```
$ module load R/3.5.1
$ module load Anaconda3/5.0.1
$ R

> library(keras)
> use_condaenv('~/.conda/envs/r-tensorflow')
> mnist <- dataset_mnist()
```
This produces the following error:
```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'tensorflow' has no attribute 'VERSION'
```

Any thoughts on what I may be doing wrong? Everything seemingly installs and loads without issue, but I cannot get any `keras` functions to run without error. I have everything working fine on my local machine (Macbook Pro), but this is my first time installing `tensorflow` and `keras` on a HPC.

**Comment by dfalbel** [comment]
Are you able to run `tf_config()`? We need to find out which version of tensorflow you have installed in the python side. Also what happens when you try loading tensorflow directly from python?

**Comment by warkentinmatt** [comment]
@dfalbel I tried running `tf_config()` in `R` and got this error:

```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'tensorflow' has no attribute 'VERSION'
```

I then ran this code:

```
$ source activate r-tensorflow
(r-tensorflow) $ python
>>> import tensorflow as tf
```

And got this hairball back...

```
Traceback (most recent call last):
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by dfalbel** [comment]
I had this problem once when trying to install TensorFlow on an older version of Ubuntu. 
Try upgrading your CentOS if possible. Also I would try solutions proposed here: https://github.com/tensorflow/tensorflow/issues/5017

**Comment by skeydan** [comment]
Hi,

I think the thread @dfalbel is linking has the solution - the first thing I'd try would be not using Anaconda, but virtualenv on this system.

If that isn't feasible, I'd create a symlink as suggested:

```
cd /n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/
ln -s /lib64/libstdc++.so.6 libstdc++.so.6
```

**Comment by dfalbel** [comment]
Having this same issue in when testing TF with anaconda. It used to work 2 days ago..

https://travis-ci.org/dfalbel/tfinstall/jobs/547843731#L1554

**Comment by dfalbel** [comment]
I fixed by using python 3.6 instead of 3.7. It's also fixable by following @skeydan comment above.

**Comment by warkentinmatt** [comment]
Hi, sorry to keep this issue going but I haven't been able to solve this issue yet. Updating the OS is not an option since I am trying to get this working on an institute-wide computing cluster. Here is what I have tried so far...

1. I tried forcing `R` to use `python 3.6.3` and still using the `conda` env `r-tensorflow`
```
$ R
> library(keras)
> use_python('/path/to/python3.6.3', require = TRUE)
> use_condaenv('/path/to/conda/envs/r-tensorflow')
> tensorflow::tf_config()
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'tensorflow' has no attribute 'VERSION'
```
This still did not work and produce the same error as before.

2. I tried using the symbolic link suggestion by @skeydan; but I got the following error.
```
$ locate libstdc++.so.6
/usr/lib/libstdc++.so.6
/usr/lib/libstdc++.so.6.0.19
/usr/lib64/libstdc++.so.6
/usr/lib64/libstdc++.so.6.0.19
$ cd /n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/
$ ln -sf usr/lib64/libstdc++.so.6 libstdc++.so.6
$ source activate r-tensorflow
(r-tensorflow) $ python
>>> import tensorflow as tf
```

The above code used the `python 3.7.3` found/installed in the `r-tensorflow` env. I tried using `python 3.6.3`, as per @dfalbel suggestion.. This version of python couldn't even find `tensorflow`...probably a PATH issue?

```
$ source activate r-tensorflow
(r-tensorflow) $ module load python/3.6.3 
(r-tensorflow) $ python
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```

I am not sure what to try next. Any advice? I suspect this is particularly annoying because I am on a computing cluster with limited write privileges (in ~ only basically), but some of the software (R, python) don't look there for packages by default.

**Comment by skeydan** [comment]
Yes, that's a difficult situation. I'd try concentrating on making things work from Python first, using 3.6 specifically as suggested by @dfalbel.

I'd recreate the `r-tensorflow` environment, like this

```
conda remove -n r-tensorflow
conda create -n r-tensorflow python=3.6
pip install tensorflow
python
```

and then

```
import tensorflow as tf
```

Does this work?

**Comment by warkentinmatt** [comment]
@skeydan Thanks for the help. Here is what I tried:

```
$ conda env remove -n r-tensorflow
$ conda create -n r-tensorflow python=3.6
$ conda install -c anaconda tensorflow -n r-tensorflow
$ source activate r-tensorflow
$ python
```
This is the error produced:
```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/n/home13/mwarkentin/.conda/envs/r-tensorflow/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.
```

**Comment by skeydan** [comment]
I think `conda` might be packaging TF in some special way.

Can you try installing using `pip` (after recreating the environment like above)?

**Comment by warkentinmatt** [comment]
Sure, this is what I tired this time around...
```
$ conda env remove -n r-tensorflow
$ conda create -n r-tensorflow python=3.6
$ source activate r-tensorflow
(r-tensorflow) $ pip install tensorflow
(r-tensorflow) $ python
```
```
>>> import tensorflow as tf
```
This seems to have worked. Next I try to get `keras` working in `R`:
```
> library(keras)
> use_condaenv('path/to/conda/env/r-tensorflow')
> tensorflow::tf_config()
TensorFlow v1.14.0 (~/.conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow)
Python v3.6 (~/.conda/envs/r-tensorflow/bin/python)
> mnist <- dataset_mnist()
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 0s 0us/step
```

Excellent! Looks like it works! Thanks for all your help. Very much appreciated. I have now closed the issue.
