### ISSUE TITLE
install_keras()

### ISSUE THREAD

**Issue by JintaoSHOU** [rstudio/keras#901]
> install_keras()
Using virtual environment '~/.virtualenvs/r-reticulate' ...
Collecting tensorflow==2.0.0
  Downloading https://files.pythonhosted.org/packages/2c/72/6b3264aa2889b7dde7663464b99587d95cd6a5f3b9b30181f14d78a63e64/tensorflow-2.0.0-cp37-cp37m-macosx_10_11_x86_64.whl (102.7MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 447, in read
    n = self.readinto(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/download.py", line 223, in written_chunks
    for chunk in chunks:
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_internal/download.py", line 212, in resp_read
    decode_content=False):
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/wjt/.virtualenvs/r-reticulate/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Error: Error installing package(s): 'tensorflow==2.0.0', 'keras', 'tensorflow-hub', 'h5py', 'pyyaml', 'requests', 'Pillow', 'scipy'

**Comment by dfalbel** [comment]
This seems like connection issues during installation. Could this be caused by a proxy?
