### ISSUE TITLE
Keras Not working 

### ISSUE THREAD

**Issue by TullioM94** [rstudio/keras#953]
Hi! 

I am trying to use Keras on Windows 10. Tensorflow works with no problems, however if I try to load the boston housing dataset I receive the following error: 

```
Error: Python module keras was not found.

Detected Python configuration:

python:         C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/tm1n18/AppData/Local/Continuum/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1
version:        3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.17.3
keras:          C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1\lib\site-packages\keras\__init__.p

python versions found: 
 C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\python.exe

```

I have tried to apply suggestions for similar problems but none of them seems to work. It seems that keras is installed but for some reason it does not work. 

Thank you in advance for the help. 

Best, 

Tullio

**Comment by dfalbel** [comment]
The Keras R package requires that the TensorFlow python package is correctly installed.
Can you try running python.exe located `C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\python.exe` and run `import tensorflow as tf` and see if it works fine?

**Comment by TullioM94** [comment]
Hi! 

Thank you so much for your answer, I have been trying to figure out it but it is complicated, I receive the following message: 


```
Traceback (most recent call last):
  File "C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

```


Thank you so much for your help, really thank you!! 

Best, 


Tullio

**Comment by TullioM94** [comment]
Hi, 

I have been working on it. I have followed the steps to uninstall and install again numpy, but the problem persists. I can give you the following additional information: 

```
> py_config()
python:         C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/tm1n18/AppData/Local/Continuum/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1
version:        3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.17.3
keras:          C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1\lib\site-packages\keras\__init__.p

python versions found: 
 C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\python.exe
```
and

```
> reticulate::py_module_available(tensorflow)
[1] FALSE
> tensorflow::tf_config()
TensorFlow v1.10.0 (C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1\lib\site-packages\keras\__init__.p)
Python v3.6 (C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\python.exe)
```
and

```
k = backend()
Error: Python module keras was not found.

Detected Python configuration:

python:         C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/tm1n18/AppData/Local/Continuum/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1
version:        3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.17.3
keras:          C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\envs\R-TENS~1\lib\site-packages\keras\__init__.p

python versions found: 
 C:\Users\tm1n18\AppData\Local\Continuum\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\tm1n18\AppData\Local\CONTIN~1\ANACON~2\python.exe
```

any input would be useful, thank you!
