### ISSUE TITLE
Error: Text Vectorization Requires Tensorflow version >= 2.1

### ISSUE THREAD

**Issue by MariaYR** [rstudio/keras#965]
I'm trying to replicate the tutorial  and run into the below error: 
```
> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night       
> library(tensorflow)
> reticulate::py_config()
python:         /Users/mboogie/Library/r-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/mboogie/Library/r-miniconda/envs/r-reticulate/lib/libpython3.6m.dylib
pythonhome:     /Users/mboogie/Library/r-miniconda/envs/r-reticulate:/Users/mboogie/Library/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:01:53)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/mboogie/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.17.4
> is_keras_available()
[1] TRUE
> num_words <- 10000
> max_length <- 50
> text_vectorization <- layer_text_vectorization(
+   max_tokens = num_words, 
+   output_sequence_length = max_length, 
+ )
Error: Text Vectorization requires TensorFlow version >= 2.1
```
I've update Tensorflow several times but somehow R doesn't recognize it. I appreciate any help.

**Comment by skeydan** [comment]
What does your `tf_config()` say?

Can you try 
```
install_tensorflow(version = "2.1")
```
?

**Comment by MariaYR** [comment]
That did it! Thank you @skeydan !

**Comment by avila-a** [comment]
Hi! I have also got into this problem.

I have tried `install_tensorflow(version = "2.1")` and `install_keras(tensorflow = 2.1)` but after doing it and having "Installation complete." I continue to have
```
> tensorflow::tf_version()
NULL
```
Furthermore, I have installed tensorflow 2.1 on my main anaconda environment with  `pip install tensorflow==2.1` but still have the same message.

```
> tensorflow::tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\aavil\Anaconda3\envs\r-reticulate\python.exe
 C:\Users\aavil\Anaconda3\python.exe
 C:\Users\aavil\Anaconda3\envs\py2\python.exe

You can install TensorFlow using the install_tensorflow() function.
```

Any idea on how could I solve this? Thanks!

**Comment by mpfp** [comment]
I'm seeing the same problem.  I've installed tensorflow with `install_tensorflow(version = "2.1-gpu", envname = "r-reticulate")` (I've also tried cpu installation).  I've also verified it is installed in the python environment.  Any help would be appreciated.  When I call `tf_version()` I get NULL.

> (r-reticulate) C:\Users\matth\Anaconda3>conda list
> packages in environment at C:\Users\matth\Anaconda3\envs\r-reticulate:
> 
>  Name                    Version                   Build  Channel
> absl-py                   0.9.0                    pypi_0    pypi
> astor                     0.8.1                    pypi_0    pypi
> cachetools                4.0.0                    pypi_0    pypi
> certifi                   2019.11.28               py36_0
> chardet                   3.0.4                    pypi_0    pypi
> gast                      0.2.2                    pypi_0    pypi
> google-auth               1.11.0                   pypi_0    pypi
> google-auth-oauthlib      0.4.1                    pypi_0    pypi
> google-pasta              0.1.8                    pypi_0    pypi
> grpcio                    1.26.0                   pypi_0    pypi
> h5py                      2.10.0                   pypi_0    pypi
> idna                      2.8                      pypi_0    pypi
> keras                     2.3.1                    pypi_0    pypi
> keras-applications        1.0.8                    pypi_0    pypi
> keras-preprocessing       1.1.0                    pypi_0    pypi
> markdown                  3.1.1                    pypi_0    pypi
> numpy                     1.18.1                   pypi_0    pypi
> oauthlib                  3.1.0                    pypi_0    pypi
> opt-einsum                3.1.0                    pypi_0    pypi
> pillow                    7.0.0                    pypi_0    pypi
> pip                       20.0.2                   py36_1
> protobuf                  3.11.2                   pypi_0    pypi
> pyasn1                    0.4.8                    pypi_0    pypi
> pyasn1-modules            0.2.8                    pypi_0    pypi
> python                    3.6.10               h9f7ef89_0
> pyyaml                    5.3                      pypi_0    pypi
> requests                  2.22.0                   pypi_0    pypi
> requests-oauthlib         1.3.0                    pypi_0    pypi
> rsa                       4.0                      pypi_0    pypi
> scipy                     1.4.1                    pypi_0    pypi
> setuptools                45.1.0                   py36_0
> six                       1.14.0                   pypi_0    pypi
> sqlite                    3.30.1               he774522_0
> tensorboard               2.1.0                    pypi_0    pypi
> **tensorflow                2.1.0                    pypi_0    pypi
> tensorflow-estimator      2.0.1                    pypi_0    pypi
> tensorflow-gpu            2.1.0                    pypi_0    pypi
> tensorflow-gpu-estimator  2.1.0                    pypi_0    pypi
> tensorflow-hub            0.7.0                    pypi_0    pypi**
> termcolor                 1.1.0                    pypi_0    pypi
> urllib3                   1.25.8                   pypi_0    pypi
> vc                        14.1                 h0510ff6_4
> vs2015_runtime            14.16.27012          hf0eaf9b_1
> werkzeug                  0.16.1                   pypi_0    pypi
> wheel                     0.34.1                   py36_0
> wincertstore              0.2              py36h7fe50ca_0
> wrapt                     1.11.2                   pypi_0    pypi

**Comment by dfalbel** [comment]
Can you please try importing TensorFlow directly in the python side and see if there's any error. You can do this by clicking twice in this file: `C:\Users\aavil\Anaconda3\envs\r-reticulate\python.exe` and the runing `import tensorflow` in the prompt.

**Comment by mpfp** [comment]
It doesn't import.  Is this is an issue of incompatible versions of Tensorflow and CUDA/CUDNN?

```(r-reticulate) C:\Users\matth>python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\matth\Anaconda3\envs\r-reticulate\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.```

**Comment by dfalbel** [comment]
This looks like an issue with cuda/cudnn or maybe issues with old processors.

**Comment by Mihiretukebede** [comment]
I have the same problem. Any help is much appreciated. Thank you. 
![image](https://user-images.githubusercontent.com/44161975/91547657-88b6d780-e924-11ea-9881-492aa636e418.png). 

R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.16  tensorflow_2.2.0 purrr_0.3.3      ggplot2_3.3.0   
[5] dplyr_1.0.0      keras_2.3.0.0    quanteda_2.0.1  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3         lattice_0.20-38    assertthat_0.2.1   zeallot_0.1.0     
 [5] glmnet_4.0-2       digest_0.6.25      foreach_1.5.0      mime_0.9          
 [9] R6_2.4.1           pillar_1.4.4       tfruns_1.4         rlang_0.4.6       
[13] rstudioapi_0.11    data.table_1.12.8  whisker_0.4        Matrix_1.2-18     
[17] shinythemes_1.1.2  splines_3.6.3      gower_0.2.1        htmlwidgets_1.5.1 
[21] munsell_0.5.0      shiny_1.5.0        compiler_3.6.3     httpuv_1.5.4      
[25] xfun_0.15          base64enc_0.1-3    pkgconfig_2.0.3    shape_1.4.4       
[29] htmltools_0.5.0    tidyselect_1.1.0   tibble_3.0.1       lgr_0.3.4         
[33] codetools_0.2-16   fansi_0.4.1        withr_2.2.0        crayon_1.3.4      
[37] later_1.1.0.1      rappdirs_0.3.1     grid_3.6.3         jsonlite_1.6.1    
[41] xtable_1.8-4       gtable_0.3.0       lifecycle_0.2.0    magrittr_1.5      
[45] scales_1.1.1       RcppParallel_5.0.1 cli_2.0.2          stringi_1.4.6     
[49] fs_1.3.1           promises_1.1.1     ellipsis_0.3.1     stopwords_2.0     
[53] generics_0.0.2     vctrs_0.3.1        fastmatch_1.1-0    xgboost_1.1.1.1   
[57] iterators_1.0.12   tools_3.6.3        lime_0.5.1         glue_1.4.1        
[61] fastmap_1.0.1      survival_3.1-8     colorspace_1.4-1   knitr_1.29        
[65] usethis_1.6.1

**Comment by erkanozhan** [comment]
Hi, 
install.packages("tensorflow")
Then, use the install_tensorflow() function to install TensorFlow. Note that on Windows you need a working installation of Anaconda.

library(tensorflow)
install_tensorflow()

> I have the same problem. Any help is much appreciated. Thank you.
> ![image](https://user-images.githubusercontent.com/44161975/91547657-88b6d780-e924-11ea-9881-492aa636e418.png).
> 
> `sessionInfo()`
> 
> R version 3.6.3 (2020-02-29)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 17763)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252 LC_CTYPE=English_United States.1252
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
> [5] LC_TIME=English_United States.1252
> 
> attached base packages:
> [1] stats graphics grDevices utils datasets methods base
> 
> other attached packages:
> [1] reticulate_1.16 tensorflow_2.2.0 purrr_0.3.3 ggplot2_3.3.0
> [5] dplyr_1.0.0 keras_2.3.0.0 quanteda_2.0.1
> 
> loaded via a namespace (and not attached):
> [1] Rcpp_1.0.3 lattice_0.20-38 assertthat_0.2.1 zeallot_0.1.0
> [5] glmnet_4.0-2 digest_0.6.25 foreach_1.5.0 mime_0.9
> [9] R6_2.4.1 pillar_1.4.4 tfruns_1.4 rlang_0.4.6
> [13] rstudioapi_0.11 data.table_1.12.8 whisker_0.4 Matrix_1.2-18
> [17] shinythemes_1.1.2 splines_3.6.3 gower_0.2.1 htmlwidgets_1.5.1
> [21] munsell_0.5.0 shiny_1.5.0 compiler_3.6.3 httpuv_1.5.4
> [25] xfun_0.15 base64enc_0.1-3 pkgconfig_2.0.3 shape_1.4.4
> [29] htmltools_0.5.0 tidyselect_1.1.0 tibble_3.0.1 lgr_0.3.4
> [33] codetools_0.2-16 fansi_0.4.1 withr_2.2.0 crayon_1.3.4
> [37] later_1.1.0.1 rappdirs_0.3.1 grid_3.6.3 jsonlite_1.6.1
> [41] xtable_1.8-4 gtable_0.3.0 lifecycle_0.2.0 magrittr_1.5
> [45] scales_1.1.1 RcppParallel_5.0.1 cli_2.0.2 stringi_1.4.6
> [49] fs_1.3.1 promises_1.1.1 ellipsis_0.3.1 stopwords_2.0
> [53] generics_0.0.2 vctrs_0.3.1 fastmatch_1.1-0 xgboost_1.1.1.1
> [57] iterators_1.0.12 tools_3.6.3 lime_0.5.1 glue_1.4.1
> [61] fastmap_1.0.1 survival_3.1-8 colorspace_1.4-1 knitr_1.29
> [65] usethis_1.6.1
