### ISSUE TITLE
Tensorboard doesn't start

### ISSUE THREAD

**Issue by tsengj** [rstudio/keras#993]
https://github.com/rstudio/tensorflow/issues/400

What does this mean?

```
> tensorboard("logs/run_a")
Error: invalid version specification ‘2020-02-15 23:19:54.907995: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll’, ‘Traceback (most recent call last):’, ‘  File "c:\users\james\appdata\local\r-mini~1\envs\r-reti~1\lib\runpy.py", line 193, in _run_module_as_main’, ‘    "__main__", mod_spec)’, ‘  File "c:\users\james\appdata\local\r-mini~1\envs\r-reti~1\lib\runpy.py", line 85, in _run_code’, ‘    exec(code, run_globals)’, ‘  File "C:\Users\james\AppData\Local\R-MINI~1\envs\R-RETI~1\Scripts\TENSOR~1.EXE\__main__.py", line 4, in <module>’, ‘  File "c:\users\james\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\tensorboard\main.py", line 44, in <module>’, ‘    from tensorboard.uploader import uploader_main’, ‘  File "c:\users\james\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\tensorboard\uploader\uploader_main.py", line 30, in <module>’, ‘    import grpc’, ‘  File "c:\users\james\appdata\local\r-mini~1\e
In addition: Warning message:
In system("tensorboard --version_tb", intern = TRUE) :
  running command 'tensorboard --version_tb' had status 1
> reticulate::py_module_available('tensorboard')
[1] TRUE
> tensorflow::tf_config()
TensorFlow v2.0.0 ()
Python v3.6 (C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate/python.exe)
> reticulate::py_config()
python:         C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.1
> 
```

**Comment by dfalbel** [comment]
This is related to: https://github.com/rstudio/tensorflow/issues/407

**Comment by tsengj** [comment]
I have the same issues with tensorboard. I've reinstalled everything R Base, Rstudio, Anaconda.
Here is my system environments. Running on Windows 10 - 64

```
Restarting R session...

> tensorflow::tf_config()
2020-05-18 22:39:42.681172: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
TensorFlow v2.2.0 (C:\Users\james\ANACON~1\envs\R-RETI~1\lib\site-packages\tensorflow\__init__.p)
Python v3.6 (C:/Users/james/anaconda3/envs/r-reticulate/python.exe)
> reticulate::py_config()
python:         C:/Users/james/anaconda3/envs/r-reticulate/python.exe
libpython:      C:/Users/james/anaconda3/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/james/anaconda3/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/james/anaconda3/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.4
tensorflow:     C:\Users\james\ANACON~1\envs\R-RETI~1\lib\site-packages\tensorflow\__init__.p

python versions found: 
 C:/Users/james/anaconda3/envs/r-reticulate/python.exe
 C:/Users/james/anaconda3/python.exe
 C:/Users/james/AppData/Local/Programs/Python/Python38/python.exe
> library(reticulate)
> conda_list()
          name                                                      python
1    anaconda3                     C:\\Users\\james\\anaconda3\\python.exe
2 r-reticulate C:\\Users\\james\\anaconda3\\envs\\r-reticulate\\python.exe
```

Tensorflow works
```
> library(tensorflow)
> a <- tf$random$normal(list(10L, 10L))
2020-05-18 22:41:59.277475: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-05-18 22:41:59.298251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GT 1030 computeCapability: 6.1
coreClock: 1.468GHz coreCount: 3 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 44.76GiB/s
2020-05-18 22:41:59.298645: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-05-18 22:41:59.304303: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-05-18 22:41:59.308025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-05-18 22:41:59.309394: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-05-18 22:41:59.314176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-05-18 22:41:59.317176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-05-18 22:41:59.326702: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-05-18 22:41:59.327424: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-05-18 22:41:59.327990: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-05-18 22:41:59.335321: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x207f92ec430 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-18 22:41:59.335685: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-18 22:41:59.336391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GT 1030 computeCapability: 6.1
coreClock: 1.468GHz coreCount: 3 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 44.76GiB/s
2020-05-18 22:41:59.336960: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-05-18 22:41:59.337170: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-05-18 22:41:59.337336: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-05-18 22:41:59.337584: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-05-18 22:41:59.337793: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-05-18 22:41:59.338028: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-05-18 22:41:59.338205: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-05-18 22:41:59.338705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-05-18 22:41:59.988951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-18 22:41:59.989247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-05-18 22:41:59.989423: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-05-18 22:41:59.990224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1347 MB memory) -> physical GPU (device: 0, name: GeForce GT 1030, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-05-18 22:41:59.992874: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x207f3b25de0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-05-18 22:41:59.993138: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GT 1030, Compute Capability 6.1
> b <- tf$random$normal(list(10L, 10L))
> tf$matmul(a, b)
2020-05-18 22:42:00.137330: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
tf.Tensor(
[[-7.5888743  -4.617306   -4.602068   -4.9077115  13.553754   -5.0759554
  -5.960786   -1.2367351  -8.003681    2.7895713 ]
 [-4.4268975   1.8936435  -1.5391005  -3.6644876   5.345785   -0.5341439
   0.37573278  3.9760878  -1.0833403  -0.5480319 ]
 [ 3.1633735   1.3282518   4.5617003  -0.35110712 -3.9477904   1.7025654
   2.1142893  -0.33294225  4.508003    1.4589938 ]
 [ 1.4492617   0.96529144  0.73098963  2.8519323   1.8277345  -0.93364847
   2.246132   -2.1135662  -4.8572497   0.7917995 ]
 [ 0.52551395 -0.05665594 -0.07006426  1.5394514   3.9560428  -2.0729616
  -2.6824265  -1.98817    -4.3975463   0.1701684 ]
 [-0.6474584   5.2523184  -2.169083    1.0151098   5.0341363   0.38750827
  -1.7311571   1.9432464  -4.120586   -1.2902467 ]
 [ 1.1628404   0.32416683  0.8367882   2.2673056  -2.802574   -0.3450417
  -0.77932906  6.6299467   4.7291636  -0.82192785]
 [-0.8696563   2.0810928  -1.9200773   1.079363    0.6262002   0.23553848
  -1.3771038   0.48130858 -4.3242655   2.6858215 ]
 [-2.1008081  -5.613517   -3.399393   -3.6729252   0.22289169 -0.43438292
  -4.0566454   2.0448103   4.818816    3.9120512 ]
 [ 1.1212018   4.201227   -7.240103   -0.366809   -0.85418665  3.4814205
  -6.2447205   1.9410825  -1.2876751   3.5875955 ]], shape=(10, 10), dtype=float32)
```

but tensorboard does not
```
> tensorboard("mnist")
Error: invalid version specification ‘2020-05-18 22:43:20.793798: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll’
```

I've previously generated the log data into 'mnist' above

Please help!
